## Configuración del Entorno e Importaciones

In [ ]:
import os
import random
import time
import urllib.parse
import requests
import numpy as np
import pandas as pd
from tqdm import tqdm
import torchaudio 
import warnings

from birdnetlib import Recording
from birdnetlib.analyzer import Analyzer

# Configurar determinismo para asegurar reproducibilidad
SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# Configuración de rutas relativas (subiendo un nivel desde la carpeta notebooks/)
BASE_DIR = "../dataset_aves"
METADATA_PATH = os.path.join(BASE_DIR, "df_metadata_audios.csv")
LABELS_PATH = os.path.join(BASE_DIR, "df_etiquetas_fuertes.csv")

# Crear los directorios base si no existen físicamente en la máquina
os.makedirs(BASE_DIR, exist_ok=True)
os.makedirs("../artifacts", exist_ok=True)

print("Inicialización completa.")
print(f"Ruta absoluta del dataset de aves: {os.path.abspath(BASE_DIR)}")

# Silenciar logs internos de compilación de TensorFlow
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 

# Ignorar advertencias de descarte de módulos de TensorFlow
warnings.filterwarnings("ignore", category=UserWarning, module="tensorflow")

Inicialización completa.
Ruta absoluta del dataset de aves: /home/els4nchez/Pictures/Bird-Recognition-using-BioSED-model/dataset_aves

# BioSED: Notebook 1 - Adquisición de Datos y Pseudo-Etiquetado Temporal

## 1. Introducción y Contexto Metodológico

Este proyecto aborda el problema de **Detección de Eventos Sonoros Bioacústicos** (BioSED - *Bioacoustic Sound Event Detection*). A diferencia de la clasificación de audio estándar, donde se predice una única etiqueta global por clip, BioSED formula un problema más complejo: **identificar simultáneamente qué especie vocaliza y en qué intervalos temporales exactos ocurre la vocalización** (clasificación frame-a-frame).

Desde la perspectiva del Aprendizaje Estadístico, este problema se modela como un sistema débilmente supervisado de múltiples etiquetas en el tiempo. La adquisición de anotaciones manuales detalladas (segmentos fuertes hechos por humanos) es altamente costosa. Por lo tanto, implementaremos un flujo de trabajo basado en **pseudo-etiquetado**:
1. **Adquisición**: Descargamos audios crudos en formato `.mp3` de la plataforma de ciencia ciudadana *Xeno-Canto*, filtrados para Colombia.
2. **Pseudo-Anotación**: Procesamos estos audios utilizando el modelo *BirdNET* de Cornell, un detector acústico robusto, para extraer segmentos con alta confianza donde se detecta canto activo.
3. **Modelado**: El modelo final (una Red Neuronal Convolucional Recurrente o CRNN) se entrenará para imitar y generalizar estas anotaciones a nivel de fotograma (*frame-level*).

### Especies Objetivo
Nos enfocamos en 10 de las especies de aves más comunes y acústicamente activas en Medellín (Valle de Aburrá):
* *Turdus ignobilis* (Mirla)
* *Pitangus sulphuratus* (Bichofué)
* *Thraupis episcopus* (Azulejo común)
* *Zonotrichia capensis* (Copetón)
* *Tyrannus melancholicus* (Sirirí)
* *Pygochelidon cyanoleuca* (Golondrina barranquera)
* *Troglodytes aedon* (Cucarachero)
* *Crotophaga ani* (Garrapatero)
* *Thraupis palmarum* (Azulejo palmero)
* *Campylorhynchus griseus* (Cucarachero chupahuevo)

## 3. Selección y Definición de las 10 Especies Objetivo

Para garantizar la viabilidad del detector acústico, seleccionamos 10 especies de aves de gran abundancia y representatividad acústica en la zona urbana del Valle de Aburrá (Medellín, Colombia). Esta selección nos permite acotar el vocabulario del modelo a clases con alta presencia de vocalizaciones en la base de datos abierta de *Xeno-Canto*, facilitando la recopilación de datos con buena relación señal-ruido.

In [2]:
especies_info = {
    "Turdus ignobilis": {
        "nombre_comun": "Mirla / Mayo",
        "nombre_ingles": "Black-billed Thrush",
        "justificacion": "Muy abundante en parques urbanos. Canto territorial continuo, melodioso y potente, con picos de actividad al amanecer."
    },
    "Pitangus sulphuratus": {
        "nombre_comun": "Bichofué / Bienteveo",
        "nombre_ingles": "Great Kiskadee",
        "justificacion": "Muy adaptado a entornos urbanos. Su vocalización onomatopéyica ('bicho-fué') es estridente, repetitiva y de fácil detección."
    },
    "Thraupis episcopus": {
        "nombre_comun": "Azulejo Común",
        "nombre_ingles": "Blue-gray Tanager",
        "justificacion": "Omnipresente en el Valle de Aburrá. Sus vocalizaciones consisten en silbidos agudos, rápidos y ligeramente chirriantes."
    },
    "Zonotrichia capensis": {
        "nombre_comun": "Copetón / Gorrión",
        "nombre_ingles": "Rufous-collared Sparrow",
        "justificacion": "El gorrión urbano por excelencia de los Andes colombianos. Canto territorial corto consistente en silbidos seguidos de un trino rápido."
    },
    "Tyrannus melancholicus": {
        "nombre_comun": "Sirirí / Suirirí",
        "nombre_ingles": "Tropical Kingbird",
        "justificacion": "Posado típicamente en cables de energía y postes. Emite series rápidas de trinos agudos y metálicos de carácter territorial."
    },
    "Pygochelidon cyanoleuca": {
        "nombre_comun": "Golondrina Barranquera",
        "nombre_ingles": "Blue-and-white Swallow",
        "justificacion": "Frecuenta bordes de construcciones y quebradas urbanas. Sus vocalizaciones consisten en zumbidos rápidos emitidos frecuentemente al vuelo."
    },
    "Troglodytes aedon": {
        "nombre_comun": "Cucarachero Común",
        "nombre_ingles": "House Wren",
        "justificacion": "Pequeño y ruidoso, habita jardines y rendijas de estructuras. Posee un canto complejo de cascadas de gorjeos rápidos y trinos intensos."
    },
    "Crotophaga ani": {
        "nombre_comun": "Garrapatero / Garrapatuelo",
        "nombre_ingles": "Smooth-billed Ani",
        "justificacion": "Habita zonas verdes abiertas y parches de maleza urbana. Emiten silbidos quejumbrosos, agudos y ascendentes de manera gregaria."
    },
    "Thraupis palmarum": {
        "nombre_comun": "Azulejo Palmero",
        "nombre_ingles": "Palm Tanager",
        "justificacion": "Estrechamente asociado a palmeras urbanas. Sus cantos son chirriantes y rápidos, planteando un reto de clasificación frente a T. episcopus."
    },
    "Campylorhynchus griseus": {
        "nombre_comun": "Cucarachero Chupahuevo / Matraca",
        "nombre_ingles": "Bicolored Wren",
        "justificacion": "Frecuente en árboles ornamentales densos. Emite vocalizaciones ásperas y sumamente ruidosas coordinadas en grupos familiares."
    }
}

# Generar lista plana para búsquedas rápidas en la API de Xeno-Canto
especies_medellin = list(especies_info.keys())

# Mostrar la tabla descriptiva como un DataFrame de Pandas para la documentación del notebook
df_especies = pd.DataFrame.from_dict(especies_info, orient="index")
df_especies.index.name = "Nombre Científico"
df_especies.reset_index(inplace=True)
display(df_especies)

,Nombre Científico,nombre_comun,nombre_ingles,justificacion
0,Turdus ignobilis,Mirla / Mayo,Black-billed Thrush,Muy abundante en parques urbanos. Canto territ...
1,Pitangus sulphuratus,Bichofué / Bienteveo,Great Kiskadee,Muy adaptado a entornos urbanos. Su vocalizaci...
2,Thraupis episcopus,Azulejo Común,Blue-gray Tanager,Omnipresente en el Valle de Aburrá. Sus vocali...
3,Zonotrichia capensis,Copetón / Gorrión,Rufous-collared Sparrow,El gorrión urbano por excelencia de los Andes ...
4,Tyrannus melancholicus,Sirirí / Suirirí,Tropical Kingbird,Posado típicamente en cables de energía y post...
5,Pygochelidon cyanoleuca,Golondrina Barranquera,Blue-and-white Swallow,Frecuenta bordes de construcciones y quebradas...
6,Troglodytes aedon,Cucarachero Común,House Wren,"Pequeño y ruidoso, habita jardines y rendijas ..."
7,Crotophaga ani,Garrapatero / Garrapatuelo,Smooth-billed Ani,Habita zonas verdes abiertas y parches de male...
8,Thraupis palmarum,Azulejo Palmero,Palm Tanager,Estrechamente asociado a palmeras urbanas. Sus...
9,Campylorhynchus griseus,Cucarachero Chupahuevo / Matraca,Bicolored Wren,Frecuente en árboles ornamentales densos. Emit...

## 4. Implementación de la Descarga de Audios desde Xeno-Canto

Para obtener las señales de audio consumiremos la API pública de **Xeno-Canto (Versión 3)**. La consulta se estructura filtrando específicamente por especie (`sp:"Nombre Científico"`) y restringiendo la localización geográfica a Colombia (`cnt:colombia`) con el fin de priorizar variaciones y modulaciones acústicas locales.

Para respetar los límites de la API de Xeno-Canto y evitar bloqueos por tasa de peticiones, la función implementa un retardo forzado de un segundo (`time.sleep(1)`) entre descargas exitosas, además de una verificación local para evitar re-descargar archivos que ya existan en el sistema.

In [3]:
# API Key oficial provista por Xeno-Canto
API_KEY = "f803b7018e2a9638e0c9c50998f681bcb1b1042f"

def descargar_de_xeno_canto(especie_nombre, max_archivos=120, base_dir="../dataset_aves"):
    """
    Busca grabaciones de una especie en la API de Xeno-Canto v3 filtradas por país (Colombia)
    y las descarga organizadamente en carpetas locales en formato MP3.
    """
    nombre_carpeta = especie_nombre.replace(" ", "_")
    carpeta_especie = os.path.join(base_dir, nombre_carpeta)
    os.makedirs(carpeta_especie, exist_ok=True)

    print(f"\nBuscando en API de Xeno-Canto: {especie_nombre} ...")

    # Usamos espacio para separar criterios y pasamos parámetros de forma limpia a requests
    params = {
        "query": f'sp:"{especie_nombre}" cnt:colombia',
        "key": API_KEY
    }
    url = "https://xeno-canto.org/api/3/recordings"

    try:
        # requests.get codificará automáticamente los espacios como '+' de forma válida
        respuesta = requests.get(url, params=params, timeout=15)
        respuesta.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"  [Error] Fallo en la petición de búsqueda a Xeno-Canto: {e}")
        return

    datos = respuesta.json()
    grabaciones = datos.get('recordings', [])
    cant_disponible = len(grabaciones)
    descargas = min(max_archivos, cant_disponible)

    if descargas == 0:
        print("  - No se hallaron grabaciones que cumplan el criterio geográfico para esta especie.")
        return

    print(f"  - Grabaciones disponibles: {cant_disponible}. Cantidad a descargar: {descargas}...")

    guardados_exito = 0
    for grabacion in grabaciones[:descargas]:
        audio_url = grabacion.get('file')
        if not audio_url:
            continue

        ruta_archivo = os.path.join(carpeta_especie, f"{grabacion['id']}.mp3")

        if not os.path.exists(ruta_archivo):
            try:
                res_audio = requests.get(audio_url, timeout=30)
                if res_audio.status_code == 200:
                    with open(ruta_archivo, 'wb') as f:
                        f.write(res_audio.content)
                    guardados_exito += 1
                
                # Pausa prudencial entre descargas consecutivas
                time.sleep(1)
            except Exception as e:
                print(f"  [Error] No se pudo descargar la grabación ID {grabacion['id']}: {e}")
        else:
            guardados_exito += 1

    print(f"  - Completado: {guardados_exito}/{descargas} archivos en '{carpeta_especie}'.")

## 5. Extracción y Compilación de Metadatos Científicos

Para garantizar el rigor metodológico del dataset, recopilaremos y estructuraremos un registro de metadatos completo por cada audio gestionado. Esto nos permitirá auditar sesgos geográficos, de calidad o de autoría antes del modelado estadístico.

Las variables que extraeremos de cada registro JSON son:
*   `id_audio`: Identificador numérico único de la grabación en Xeno-Canto.
*   `especie_esperada`: Nombre de la carpeta objetivo de la descarga.
*   `genero` / `especie_nombre`: Taxonomía oficial registrada.
*   `autor` / `licencia`: Propiedad intelectual y tipo de licencia de uso.
*   `pais` / `localidad` / `latitud` / `longitud`: Contexto geográfico del registro.
*   `calidad`: Calificación de la grabación (escala A a E asignada por la comunidad).
*   `duracion_original`: Duración del archivo de audio original antes del procesamiento.
*   `formato`: Extensión del archivo original (típicamente MP3).
*   `tipo_vocalizacion`: Tipo de sonido registrado (canto, llamado, etc.).
*   `url_descarga`: Enlace directo de descarga.

In [4]:
# Inicializar lista para almacenar los diccionarios de metadatos
metadatos_audios = []

# Ajustar volumen de descarga (puedes cambiarlo a 120 para el dataset completo de entrenamiento)
MAX_ARCHIVOS_POR_ESPECIE = 120 

print(f"Iniciando descarga física y compilación de metadatos de audios...")
print(f"Configuración actual: Máximo {MAX_ARCHIVOS_POR_ESPECIE} audios por especie.")

for especie in especies_medellin:
    # 1. Invocar la descarga física utilizando la nueva versión corregida con params
    descargar_de_xeno_canto(especie, max_archivos=MAX_ARCHIVOS_POR_ESPECIE, base_dir=BASE_DIR)
    
    # 2. Consultar la API usando parámetros limpios para recopilar los metadatos de las mismas descargas
    params = {
        "query": f'sp:"{especie}" cnt:colombia',
        "key": API_KEY
    }
    url = "https://xeno-canto.org/api/3/recordings"
    
    try:
        respuesta = requests.get(url, params=params, timeout=15)
        if respuesta.status_code == 200:
            grabaciones = respuesta.json().get('recordings', [])
            
            for grabacion in grabaciones[:MAX_ARCHIVOS_POR_ESPECIE]:
                metadatos_audios.append({
                    "id_audio": grabacion.get("id"),
                    "especie_esperada": especie,
                    "genero": grabacion.get("gen"),
                    "especie_nombre": grabacion.get("sp"),
                    "nombre_ingles": grabacion.get("en"),
                    "autor": grabacion.get("rec"),
                    "pais": grabacion.get("cnt"),
                    "localidad": grabacion.get("loc"),
                    "latitud": grabacion.get("lat"),
                    "longitud": grabacion.get("lng"),
                    "calidad": grabacion.get("q"),
                    "duracion_original": grabacion.get("length"),
                    "licencia": grabacion.get("lic"),
                    "formato": grabacion.get("fmt"),
                    "url_descarga": grabacion.get("file"),
                    "tipo_vocalizacion": grabacion.get("type"),
                    "fecha_registro": grabacion.get("date")
                })
    except Exception as e:
        print(f"  [Advertencia] No se pudieron compilar metadatos para {especie}: {e}")

# Construir el DataFrame de metadatos a partir de la lista acumulada
df_metadata_completa = pd.DataFrame(metadatos_audios)

print(f"\nProceso finalizado.")
print(f"Total de registros de metadatos almacenados en memoria: {len(df_metadata_completa)}")

# Mostrar una muestra del DataFrame resultante si no está vacío
if not df_metadata_completa.empty:
    display(df_metadata_completa.head(5))

Iniciando descarga física y compilación de metadatos de audios...
Configuración actual: Máximo 120 audios por especie.

Buscando en API de Xeno-Canto: Turdus ignobilis ...
  - Grabaciones disponibles: 62. Cantidad a descargar: 62...
  - Completado: 62/62 archivos en '../dataset_aves/Turdus_ignobilis'.

Buscando en API de Xeno-Canto: Pitangus sulphuratus ...
  - Grabaciones disponibles: 100. Cantidad a descargar: 100...
  - Completado: 100/100 archivos en '../dataset_aves/Pitangus_sulphuratus'.

Buscando en API de Xeno-Canto: Thraupis episcopus ...
  - Grabaciones disponibles: 71. Cantidad a descargar: 71...
  - Completado: 71/71 archivos en '../dataset_aves/Thraupis_episcopus'.

Buscando en API de Xeno-Canto: Zonotrichia capensis ...
  - Grabaciones disponibles: 100. Cantidad a descargar: 100...
  - Completado: 100/100 archivos en '../dataset_aves/Zonotrichia_capensis'.

Buscando en API de Xeno-Canto: Tyrannus melancholicus ...
  - Grabaciones disponibles: 86. Cantidad a descargar: 86...
  - Completado: 86/86 archivos en '../dataset_aves/Tyrannus_melancholicus'.

Buscando en API de Xeno-Canto: Pygochelidon cyanoleuca ...
  - Grabaciones disponibles: 33. Cantidad a descargar: 33...
  - Completado: 33/33 archivos en '../dataset_aves/Pygochelidon_cyanoleuca'.

Buscando en API de Xeno-Canto: Troglodytes aedon ...
  - Grabaciones disponibles: 100. Cantidad a descargar: 100...
  - Completado: 100/100 archivos en '../dataset_aves/Troglodytes_aedon'.

Buscando en API de Xeno-Canto: Crotophaga ani ...
  - Grabaciones disponibles: 83. Cantidad a descargar: 83...
  - Completado: 83/83 archivos en '../dataset_aves/Crotophaga_ani'.

Buscando en API de Xeno-Canto: Thraupis palmarum ...
  - Grabaciones disponibles: 46. Cantidad a descargar: 46...
  - Completado: 46/46 archivos en '../dataset_aves/Thraupis_palmarum'.

Buscando en API de Xeno-Canto: Campylorhynchus griseus ...
  - Grabaciones disponibles: 74. Cantidad a descargar: 74...
  - Completado: 74/74 archivos en '../dataset_aves/Campylorhynchus_griseus'.

Proceso finalizado.
Total de registros de metadatos almacenados en memoria: 755

,id_audio,especie_esperada,genero,especie_nombre,nombre_ingles,autor,pais,localidad,latitud,longitud,calidad,duracion_original,licencia,formato,url_descarga,tipo_vocalizacion,fecha_registro
0,742378,Turdus ignobilis,Turdus,ignobilis,Black-billed Thrush,Joost van Bruggen,Colombia,"Victoria, Caldas",5.3191,None,A,0:50,https://creativecommons.org/licenses/by-nc-nd/...,None,https://xeno-canto.org/742378/download,call,2022-07-03
1,742377,Turdus ignobilis,Turdus,ignobilis,Black-billed Thrush,Joost van Bruggen,Colombia,"Victoria, Caldas",5.3191,None,A,0:04,https://creativecommons.org/licenses/by-nc-nd/...,None,https://xeno-canto.org/742377/download,alarm call,2022-07-03
2,683965,Turdus ignobilis,Turdus,ignobilis,Black-billed Thrush,Mauricio Cuellar Ramirez (@Birding.travel),Colombia,"Pava Negra Nature Reserve - Florencia, Caquetá.",1.7135,None,A,0:22,https://creativecommons.org/licenses/by-nc-sa/...,None,https://xeno-canto.org/683965/download,"song, llamadas de agresión",2021-10-25
3,614016,Turdus ignobilis,Turdus,ignobilis,Black-billed Thrush,Mauricio Cuellar Ramirez (@Birding.travel),Colombia,"Finca San Jorge, Morelia/Caquetá",1.4898,None,A,0:44,https://creativecommons.org/licenses/by-nc-sa/...,None,https://xeno-canto.org/614016/download,song,2021-01-07
4,576274,Turdus ignobilis,Turdus,ignobilis,Black-billed Thrush,Jerome Fischer,Colombia,"Ukuku Rural Lodge, Juntas, Ibague, Tolima, Co...",4.5585,None,A,1:02,https://creativecommons.org/licenses/by-nc-sa/...,None,https://xeno-canto.org/576274/download,song,2020-07-15

## 6. Validación de Integridad Física y Decodificación de Audios

Un reto común al trabajar con audios distribuidos de forma abierta (como los de *Xeno-Canto*) es la presencia de archivos MP3 corruptos debido a subidas interrumpidas, formatos de tasa de bits variable no estandarizados o problemas en los códecs locales del servidor de origen. Si estos audios corruptos se ignoran, durante el modelado la librería de procesamiento fallará silenciosamente, forzando al cargador de datos a retornar matrices vacías (llesnas de ceros), lo que confunde severamente el entrenamiento de la red neuronal [5].{}+[Cexrgfolkdmñasz]

Para mitigar esto de raíz, implementaremos una **sanitización preventiva estricta**:
1. Intentaremos cargar y decodificar por completo cada archivo `.mp3` descargado utilizando `torchaudio.load()`.
2. Mediremos las propiedades acústicas de la señal real decodificada: número de canales, tasa de muestreo (*sample rate*) real y duración real medida en segundos.
3. Si la decodificación falla y lanza cualquier excepción (como errores de códecs o de lectura de tramas), **eliminaremos el archivo físicamente de la máquina** y descartaremos permanentemente su registro del DataFrame de metadatos, asegurando un dataset completamente funcional [5].

In [5]:
# Lista para registrar los índices de metadatos que presenten problemas y deban eliminarse
indices_descartar = []

# Listas para almacenar las dimensiones físicas reales medidas directamente del códec
duraciones_reales = []
sample_rates_reales = []
canales_reales = []

print("Iniciando validación física de decodificación en audios descargados...")

for idx, row in tqdm(df_metadata_completa.iterrows(), total=len(df_metadata_completa)):
    nombre_carpeta = row["especie_esperada"].replace(" ", "_")
    ruta_archivo = os.path.join(BASE_DIR, nombre_carpeta, f"{row['id_audio']}.mp3")
    
    # 1. Comprobación de existencia del archivo en disco
    if not os.path.exists(ruta_archivo):
        print(f"\n  [Advertencia] ID {row['id_audio']} ({row['especie_esperada']}) no está presente en la ruta física.")
        indices_descartar.append(idx)
        
        # CORRECCIÓN DE BUG: Añadir None para mantener el alineamiento antes del drop
        duraciones_reales.append(None)
        sample_rates_reales.append(None)
        canales_reales.append(None)
        continue
        
    # 2. Intento de decodificación física del stream de audio
    try:
        # Intentamos decodificar las tramas completas del archivo con torchaudio
        waveform, sr = torchaudio.load(ruta_archivo)
        
        # Extraer metadatos acústicos reales medidos directamente
        num_canales = waveform.shape[0]
        num_frames = waveform.shape[1]
        duracion_segundos = num_frames / sr
        
        # Almacenar las propiedades medidas
        duraciones_reales.append(duracion_segundos)
        sample_rates_reales.append(sr)
        canales_reales.append(num_canales)
        
    except Exception as e:
        # Reportar fallo y proceder a eliminar el archivo corrupto del almacenamiento local
        print(f"\n  [Archivo Corrupto] Falló decodificación de ID {row['id_audio']} ({row['especie_esperada']}).")
        print(f"  -> Causa: {e}")
        print(f"  -> Eliminando archivo corrupto de forma física del disco...")
        
        # Eliminar archivo físico para no contaminar pipelines posteriores
        try:
            os.remove(ruta_archivo)
        except Exception as err_del:
            print(f"    [Error] No se pudo remover el archivo del disco: {err_del}")
            
        indices_descartar.append(idx)
        
        # Llenar con nulos para mantener alineadas las listas antes del drop
        duraciones_reales.append(None)
        sample_rates_reales.append(None)
        canales_reales.append(None)

# 3. Incorporar los metadatos acústicos reales validados al DataFrame principal
df_metadata_completa["duracion_real"] = duraciones_reales
df_metadata_completa["sample_rate_real"] = sample_rates_reales
df_metadata_completa["canales_real"] = canales_reales

# 4. Descartar definitivamente los registros de metadatos de audios corruptos o ausentes
if indices_descartar:
    df_metadata_completa.drop(indices_descartar, inplace=True)
    df_metadata_completa.reset_index(drop=True, inplace=True)
    print(f"\nSaneamiento completado: Se eliminaron {len(indices_descartar)} registros corruptos o ausentes.")
else:
    print("\nÉxito: Todos los audios se decodificaron exitosamente sin errores.")

print(f"Registros válidos y verificados restantes en el DataFrame: {len(df_metadata_completa)}")

Iniciando validación física de decodificación en audios descargados...

  3%|▎         | 25/755 [00:02<00:43, 16.96it/s]

  [Archivo Corrupto] Falló decodificación de ID 433294 (Turdus ignobilis).
  -> Causa: Failed to decode audio samples: decodeAVFrame, /__w/torchcodec/torchcodec/meta-pytorch/torchcodec/src/torchcodec/_core/SingleStreamDecoder.cpp:1495, Could not push packet to decoder: Invalid data found when processing input
  -> Eliminando archivo corrupto de forma física del disco...

  4%|▍         | 30/755 [00:03<00:58, 12.31it/s]

  [Archivo Corrupto] Falló decodificación de ID 425787 (Turdus ignobilis).
  -> Causa: Failed to decode audio samples: decodeAVFrame, /__w/torchcodec/torchcodec/meta-pytorch/torchcodec/src/torchcodec/_core/SingleStreamDecoder.cpp:1495, Could not push packet to decoder: Invalid data found when processing input
  -> Eliminando archivo corrupto de forma física del disco...

 21%|██        | 160/755 [00:11<00:16, 35.19it/s]

  [Archivo Corrupto] Falló decodificación de ID 393268 (Pitangus sulphuratus).
  -> Causa: Failed to decode audio samples: decodeAVFrame, /__w/torchcodec/torchcodec/meta-pytorch/torchcodec/src/torchcodec/_core/SingleStreamDecoder.cpp:1495, Could not push packet to decoder: Invalid data found when processing input
  -> Eliminando archivo corrupto de forma física del disco...

 63%|██████▎   | 476/755 [00:23<00:09, 28.58it/s]

  [Archivo Corrupto] Falló decodificación de ID 773325 (Troglodytes aedon).
  -> Causa: Failed to decode audio samples: decodeAVFrame, /__w/torchcodec/torchcodec/meta-pytorch/torchcodec/src/torchcodec/_core/SingleStreamDecoder.cpp:1495, Could not push packet to decoder: Invalid data found when processing input
  -> Eliminando archivo corrupto de forma física del disco...

100%|██████████| 755/755 [00:34<00:00, 21.83it/s]

Saneamiento completado: Se eliminaron 4 registros corruptos o ausentes.
Registros válidos y verificados restantes en el DataFrame: 751

## 7. Generación de Pseudo-Etiquetas Temporales con BirdNET

Una vez que hemos garantizado que los 50 archivos de audio del dataset de prueba son físicamente legibles, procedemos a realizar el **pseudo-etiquetado temporal** [5]. Utilizaremos la librería `birdnetlib`, que actúa como interfaz local para el modelo de aprendizaje profundo *BirdNET* desarrollado por el *Laboratorio de Ornitología de Cornell*.

El analizador procesará cada audio completo de forma secuencial y detectará la presencia de cantos de aves en ventanas de tiempo específicas. Configuraremos un umbral de confianza mínimo intencionalmente bajo (`min_conf=0.10`) para registrar vocalizaciones sutiles o distantes que un umbral estricto omitiría. Esto es vital para SED, ya que nos permitirá contar con etiquetas temporales de cantos tenues y posteriormente aplicar filtros más estrictos si así lo deseamos.

Este proceso generará nuestra matriz base de etiquetas temporales (con marcas de `inicio_segundo` y `fin_segundo`).

In [6]:
# 1. Inicializar el analizador de BirdNET (descarga automáticamente el modelo de Cornell si es la primera ejecución)
print("Inicializando modelo de BirdNET (Analyzer)...")
analyzer = Analyzer()
print("Modelo de BirdNET cargado exitosamente.")

# Lista para acumular los eventos acústicos detectados por BirdNET
detecciones_acumuladas = []

print("\nIniciando análisis acústico sobre los audios verificados...")

for idx, row in tqdm(df_metadata_completa.iterrows(), total=len(df_metadata_completa)):
    nombre_carpeta = row["especie_esperada"].replace(" ", "_")
    nombre_archivo = f"{row['id_audio']}.mp3"
    ruta_archivo = os.path.join(BASE_DIR, nombre_carpeta, nombre_archivo)
    
    # Asegurar que el archivo físico exista en disco antes de mandarlo a analizar
    if not os.path.exists(ruta_archivo):
        continue
        
    try:
        # Instanciar el objeto de grabación de BirdNET
        recording = Recording(analyzer, ruta_archivo, min_conf=0.10)
        recording.analyze()
        
        # Extraer cada detección encontrada dentro de la grabación
        for deteccion in recording.detections:
            detecciones_acumuladas.append({
                "archivo_original": nombre_archivo,
                "especie_esperada": row["especie_esperada"],  # Carpeta de origen
                "ave_detectada_comun": deteccion.get("common_name"),
                "ave_detectada_cientifico": deteccion.get("scientific_name"),
                "inicio_segundo": deteccion.get("start_time"),
                "fin_segundo": deteccion.get("end_time"),
                "confianza_birdnet": deteccion.get("confidence")
            })
            
    except Exception as e:
        print(f"\n  [Error] Falló el análisis de BirdNET para el audio ID {row['id_audio']}: {e}")

# Convertir la lista de diccionarios en el DataFrame de etiquetas fuertes
df_etiquetas_fuertes = pd.DataFrame(detecciones_acumuladas)

print(f"\nAnálisis acústico finalizado.")
print(f"Total de segmentos de cantos (pseudo-etiquetas) detectados: {len(df_etiquetas_fuertes)}")

# Mostrar una muestra de las detecciones encontradas
if not df_etiquetas_fuertes.empty:
    display(df_etiquetas_fuertes.head(5))

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

Inicializando modelo de BirdNET (Analyzer)...
Labels loaded.
load model True
Model loaded.
Labels loaded.
load_species_list_model
Meta model loaded.
Modelo de BirdNET cargado exitosamente.

Iniciando análisis acústico sobre los audios verificados...

  0%|          | 0/751 [00:00<?, ?it/s]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 742378.mp3

  0%|          | 2/751 [00:03<16:18,  1.31s/it]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 742377.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 683965.mp3

  0%|          | 3/751 [00:04<16:00,  1.28s/it]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 614016.mp3

  1%|          | 4/751 [00:05<16:03,  1.29s/it]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 576274.mp3

  1%|          | 5/751 [00:06<15:34,  1.25s/it]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 528032.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 462015.mp3

  1%|          | 7/751 [00:07<09:35,  1.29it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 459232.mp3

  1%|          | 8/751 [00:07<08:22,  1.48it/s]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 416717.mp3

  1%|          | 9/751 [00:09<12:51,  1.04s/it]

read_audio_data
read_audio_data: complete, read  31 chunks.
analyze_recording 237854.mp3

  1%|▏         | 10/751 [00:12<18:40,  1.51s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 125997.mp3

  1%|▏         | 11/751 [00:13<16:05,  1.31s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 73162.mp3

  2%|▏         | 12/751 [00:14<14:33,  1.18s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 37316.mp3

  2%|▏         | 13/751 [00:15<13:28,  1.10s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 37272.mp3

  2%|▏         | 14/751 [00:16<13:06,  1.07s/it]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 22340.mp3

  2%|▏         | 15/751 [00:16<11:54,  1.03it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 1106129.mp3

  2%|▏         | 16/751 [00:18<12:26,  1.02s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 1069548.mp3

  2%|▏         | 17/751 [00:18<11:21,  1.08it/s]

read_audio_data
read_audio_data: complete, read  20 chunks.
analyze_recording 946956.mp3

  2%|▏         | 18/751 [00:21<16:30,  1.35s/it]

read_audio_data
read_audio_data: complete, read  20 chunks.
analyze_recording 842161.mp3

  3%|▎         | 19/751 [00:22<17:55,  1.47s/it]

read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording 742969.mp3

  3%|▎         | 20/751 [00:25<22:40,  1.86s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 674644.mp3

  3%|▎         | 21/751 [00:25<17:14,  1.42s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 582905.mp3

  3%|▎         | 22/751 [00:26<15:41,  1.29s/it]

read_audio_data
read_audio_data: complete, read  25 chunks.
analyze_recording 581238.mp3

  3%|▎         | 23/751 [00:29<18:57,  1.56s/it]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 550000.mp3

  3%|▎         | 24/751 [00:30<16:46,  1.39s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 538046.mp3

  3%|▎         | 25/751 [00:30<14:40,  1.21s/it]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 498044.mp3

  3%|▎         | 26/751 [00:32<17:22,  1.44s/it]

read_audio_data
read_audio_data: complete, read  89 chunks.
analyze_recording 432829.mp3

  4%|▎         | 27/751 [00:37<29:46,  2.47s/it]

read_audio_data
read_audio_data: complete, read  42 chunks.
analyze_recording 420238.mp3

  4%|▎         | 28/751 [00:40<29:54,  2.48s/it]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 367898.mp3

  4%|▍         | 29/751 [00:42<29:02,  2.41s/it]

read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording 327535.mp3

  4%|▍         | 30/751 [00:44<25:56,  2.16s/it]

read_audio_data
read_audio_data: complete, read  34 chunks.
analyze_recording 310058.mp3

  4%|▍         | 31/751 [00:47<29:41,  2.47s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 244910.mp3

  4%|▍         | 32/751 [00:48<25:47,  2.15s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 244726.mp3

  4%|▍         | 33/751 [00:49<19:56,  1.67s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 244725.mp3

  5%|▍         | 34/751 [00:50<17:44,  1.48s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 237885.mp3

  5%|▍         | 35/751 [00:51<15:39,  1.31s/it]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 237870.mp3

  5%|▍         | 37/751 [00:52<11:37,  1.02it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 157668.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 155830.mp3
read_audio_data
read_audio_data: complete, read  913 chunks.
analyze_recording 147860.mp3

  5%|▌         | 39/751 [02:13<3:46:35, 19.10s/it]

read_audio_data
read_audio_data: complete, read  35 chunks.
analyze_recording 129924.mp3

  5%|▌         | 40/751 [02:16<2:59:06, 15.11s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 129722.mp3

  5%|▌         | 41/751 [02:16<2:13:09, 11.25s/it]

read_audio_data
read_audio_data: complete, read  40 chunks.
analyze_recording 127028.mp3

  6%|▌         | 42/751 [02:20<1:47:56,  9.14s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 86062.mp3

  6%|▌         | 43/751 [02:20<1:19:21,  6.73s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 958936.mp3

  6%|▌         | 44/751 [02:21<58:12,  4.94s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 958200.mp3

  6%|▌         | 45/751 [02:21<44:04,  3.75s/it]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 936210.mp3
read_audio_data
read_audio_data: complete, read  47 chunks.
analyze_recording 362676.mp3

  6%|▋         | 47/751 [02:24<30:44,  2.62s/it]

read_audio_data
read_audio_data: complete, read  33 chunks.
analyze_recording 340086.mp3

  6%|▋         | 48/751 [02:27<31:57,  2.73s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 307457.mp3

  7%|▋         | 49/751 [02:28<25:30,  2.18s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 245195.mp3

  7%|▋         | 51/751 [02:28<15:00,  1.29s/it]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 163738.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 854431.mp3

  7%|▋         | 52/751 [02:29<14:01,  1.20s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 454495.mp3

  7%|▋         | 53/751 [02:30<12:02,  1.03s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 454494.mp3

  7%|▋         | 54/751 [02:30<10:35,  1.10it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 454493.mp3

  7%|▋         | 56/751 [02:31<06:24,  1.81it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 433279.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 43639.mp3
read_audio_data

  8%|▊         | 58/751 [02:31<04:06,  2.81it/s]

read_audio_data: complete, read  2 chunks.
analyze_recording 855436.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 235772.mp3

  8%|▊         | 59/751 [02:32<04:54,  2.35it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 235771.mp3

  8%|▊         | 60/751 [02:32<05:05,  2.26it/s]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 1140118.mp3

  8%|▊         | 61/751 [02:34<08:43,  1.32it/s]

read_audio_data
read_audio_data: complete, read  34 chunks.
analyze_recording 1140116.mp3

  8%|▊         | 62/751 [02:37<15:20,  1.34s/it]

read_audio_data
read_audio_data: complete, read  36 chunks.
analyze_recording 1140112.mp3

  8%|▊         | 63/751 [02:40<21:24,  1.87s/it]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 1039818.mp3

  9%|▊         | 64/751 [02:41<18:27,  1.61s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 1000546.mp3

  9%|▊         | 65/751 [02:42<16:00,  1.40s/it]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 946011.mp3

  9%|▉         | 66/751 [02:44<19:08,  1.68s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 915965.mp3

  9%|▉         | 67/751 [02:44<14:38,  1.29s/it]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 810565.mp3

  9%|▉         | 69/751 [02:45<09:37,  1.18it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 742379.mp3
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 719823.mp3

  9%|▉         | 70/751 [02:46<09:27,  1.20it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 690999.mp3

  9%|▉         | 71/751 [02:47<09:14,  1.23it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 629828.mp3

 10%|▉         | 72/751 [02:48<09:24,  1.20it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 625529.mp3

 10%|▉         | 73/751 [02:49<09:30,  1.19it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 604880.mp3

 10%|▉         | 74/751 [02:49<08:24,  1.34it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 602887.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 593047.mp3

 10%|█         | 76/751 [02:50<05:27,  2.06it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 592826.mp3

 10%|█         | 77/751 [02:50<05:04,  2.21it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 560200.mp3

 10%|█         | 78/751 [02:51<05:45,  1.95it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 558365.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 549480.mp3

 11%|█         | 80/751 [02:51<03:52,  2.88it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 544278.mp3

 11%|█         | 81/751 [02:52<05:47,  1.93it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 543429.mp3

 11%|█         | 82/751 [02:52<05:04,  2.20it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 543428.mp3

 11%|█         | 83/751 [02:53<06:13,  1.79it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 542483.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 494788.mp3

 11%|█▏        | 85/751 [02:54<05:14,  2.12it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 457242.mp3

 11%|█▏        | 86/751 [02:54<05:43,  1.94it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 437833.mp3

 12%|█▏        | 87/751 [02:56<07:54,  1.40it/s]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 433508.mp3

 12%|█▏        | 88/751 [02:57<09:46,  1.13it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 424597.mp3

 12%|█▏        | 89/751 [02:58<08:57,  1.23it/s]

read_audio_data
read_audio_data: complete, read  53 chunks.
analyze_recording 315202.mp3

 12%|█▏        | 90/751 [03:01<15:10,  1.38s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 307456.mp3

 12%|█▏        | 91/751 [03:01<11:42,  1.06s/it]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 245496.mp3

 12%|█▏        | 92/751 [03:02<10:24,  1.06it/s]

read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording 244845.mp3

 12%|█▏        | 93/751 [03:04<14:45,  1.35s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 137838.mp3

 13%|█▎        | 94/751 [03:05<13:26,  1.23s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 127206.mp3

 13%|█▎        | 95/751 [03:05<10:32,  1.04it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 124924.mp3

 13%|█▎        | 96/751 [03:06<08:46,  1.24it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 59561.mp3

 13%|█▎        | 97/751 [03:06<07:53,  1.38it/s]

read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording 1024826.mp3

 13%|█▎        | 98/751 [03:08<12:43,  1.17s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 975741.mp3

 13%|█▎        | 99/751 [03:09<11:17,  1.04s/it]

read_audio_data
read_audio_data: complete, read  22 chunks.
analyze_recording 974457.mp3

 13%|█▎        | 100/751 [03:10<11:32,  1.06s/it]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 974455.mp3

 13%|█▎        | 101/751 [03:11<10:45,  1.01it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 974206.mp3

 14%|█▍        | 104/751 [03:12<05:19,  2.03it/s]

read_audio_data
read_audio_data: complete, read  0 chunks.
analyze_recording 946185.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 946184.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 946183.mp3

 14%|█▍        | 106/751 [03:12<03:44,  2.88it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 911033.mp3
read_audio_data

 14%|█▍        | 107/751 [03:12<03:33,  3.02it/s]

read_audio_data: complete, read  3 chunks.
analyze_recording 837571.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 771667.mp3

 14%|█▍        | 108/751 [03:13<04:21,  2.46it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 763568.mp3
read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording 747002.mp3

 15%|█▍        | 110/751 [03:16<09:17,  1.15it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 743922.mp3

 15%|█▍        | 111/751 [03:17<09:15,  1.15it/s]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 742323.mp3

 15%|█▍        | 112/751 [03:18<10:28,  1.02it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 693776.mp3

 15%|█▌        | 113/751 [03:18<08:24,  1.26it/s]

read_audio_data
read_audio_data: complete, read  36 chunks.
analyze_recording 562861.mp3

 15%|█▌        | 114/751 [03:20<11:56,  1.13s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 541468.mp3

 15%|█▌        | 115/751 [03:20<09:10,  1.15it/s]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 537857.mp3

 15%|█▌        | 116/751 [03:22<10:51,  1.03s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 524053.mp3

 16%|█▌        | 117/751 [03:22<08:30,  1.24it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 524052.mp3

 16%|█▌        | 118/751 [03:23<10:17,  1.03it/s]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 524051.mp3

 16%|█▌        | 119/751 [03:25<13:16,  1.26s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 524050.mp3

 16%|█▌        | 120/751 [03:26<11:52,  1.13s/it]

read_audio_data
read_audio_data: complete, read  33 chunks.
analyze_recording 524049.mp3

 16%|█▌        | 121/751 [03:29<17:05,  1.63s/it]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 524048.mp3

 16%|█▌        | 122/751 [03:30<15:41,  1.50s/it]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 524047.mp3

 16%|█▋        | 123/751 [03:32<15:28,  1.48s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 524046.mp3

 17%|█▋        | 124/751 [03:32<12:28,  1.19s/it]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 524045.mp3

 17%|█▋        | 125/751 [03:34<14:26,  1.38s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 521097.mp3

 17%|█▋        | 126/751 [03:34<11:08,  1.07s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 438179.mp3

 17%|█▋        | 127/751 [03:35<08:49,  1.18it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 433367.mp3

 17%|█▋        | 128/751 [03:35<07:37,  1.36it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 348992.mp3

 17%|█▋        | 129/751 [03:36<07:13,  1.43it/s]

read_audio_data
read_audio_data: complete, read  25 chunks.
analyze_recording 342397.mp3

 17%|█▋        | 130/751 [03:37<09:17,  1.11it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 332326.mp3

 17%|█▋        | 131/751 [03:38<08:15,  1.25it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 317696.mp3

 18%|█▊        | 132/751 [03:39<10:03,  1.03it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 310054.mp3

 18%|█▊        | 133/751 [03:40<10:37,  1.03s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 302824.mp3

 18%|█▊        | 134/751 [03:41<09:23,  1.10it/s]

read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording 245291.mp3

 18%|█▊        | 135/751 [03:42<10:57,  1.07s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 240055.mp3

 18%|█▊        | 136/751 [03:43<10:02,  1.02it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 156310.mp3

 18%|█▊        | 137/751 [03:43<07:56,  1.29it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 148226.mp3

 18%|█▊        | 138/751 [03:44<07:14,  1.41it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 131749.mp3

 19%|█▊        | 139/751 [03:45<07:43,  1.32it/s]

read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording 129411.mp3

 19%|█▊        | 140/751 [03:46<09:40,  1.05it/s]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 128403.mp3

 19%|█▉        | 141/751 [03:47<10:08,  1.00it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 105212.mp3

 19%|█▉        | 143/751 [03:48<06:45,  1.50it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 91896.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 86104.mp3

 19%|█▉        | 144/751 [03:49<06:41,  1.51it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 59560.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 56863.mp3

 19%|█▉        | 146/751 [03:49<04:08,  2.43it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 56658.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 54684.mp3

 20%|█▉        | 148/751 [03:49<03:09,  3.19it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 54682.mp3

 20%|█▉        | 149/751 [03:50<04:10,  2.41it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 20514.mp3
read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 1069561.mp3

 20%|██        | 151/751 [03:52<06:24,  1.56it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 959536.mp3

 20%|██        | 152/751 [03:53<06:30,  1.54it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 840933.mp3

 20%|██        | 153/751 [03:53<05:31,  1.80it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 779245.mp3

 21%|██        | 154/751 [03:54<06:02,  1.65it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 432952.mp3

 21%|██        | 155/751 [03:54<05:34,  1.78it/s]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 357280.mp3

 21%|██        | 156/751 [03:56<08:52,  1.12it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 245087.mp3

 21%|██        | 157/751 [03:57<09:58,  1.01s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 245078.mp3

 21%|██        | 158/751 [03:58<09:36,  1.03it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 244867.mp3

 21%|██        | 159/751 [03:59<10:12,  1.03s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 980357.mp3

 21%|██▏       | 161/751 [04:00<06:47,  1.45it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 905403.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 774781.mp3

 22%|██▏       | 162/751 [04:00<05:47,  1.69it/s]

read_audio_data
read_audio_data: complete, read  36 chunks.
analyze_recording 742387.mp3

 22%|██▏       | 163/751 [04:02<09:35,  1.02it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 559797.mp3

 22%|██▏       | 164/751 [04:03<09:12,  1.06it/s]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 552690.mp3

 22%|██▏       | 165/751 [04:04<09:12,  1.06it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 542034.mp3

 22%|██▏       | 166/751 [04:05<07:22,  1.32it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 541886.mp3

 22%|██▏       | 167/751 [04:06<09:21,  1.04it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 521293.mp3

 22%|██▏       | 168/751 [04:07<09:02,  1.07it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 457248.mp3

 23%|██▎       | 169/751 [04:07<07:05,  1.37it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 449317.mp3

 23%|██▎       | 170/751 [04:08<07:57,  1.22it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 432832.mp3

 23%|██▎       | 171/751 [04:09<07:05,  1.36it/s]

read_audio_data
read_audio_data: complete, read  29 chunks.
analyze_recording 424378.mp3

 23%|██▎       | 172/751 [04:10<09:18,  1.04it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 421098.mp3

 23%|██▎       | 173/751 [04:11<07:42,  1.25it/s]

read_audio_data
read_audio_data: complete, read  26 chunks.
analyze_recording 245125.mp3

 23%|██▎       | 174/751 [04:12<09:25,  1.02it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 236212.mp3

 23%|██▎       | 175/751 [04:13<09:44,  1.01s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 236211.mp3

 23%|██▎       | 176/751 [04:14<09:01,  1.06it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 163749.mp3

 24%|██▎       | 177/751 [04:14<07:05,  1.35it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 129721.mp3

 24%|██▎       | 178/751 [04:15<08:16,  1.15it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 57493.mp3

 24%|██▍       | 179/751 [04:16<06:47,  1.40it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 18236.mp3

 24%|██▍       | 180/751 [04:16<06:42,  1.42it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 1140407.mp3

 24%|██▍       | 181/751 [04:18<08:24,  1.13it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 980365.mp3

 24%|██▍       | 182/751 [04:18<08:04,  1.17it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 946267.mp3

 25%|██▍       | 185/751 [04:19<04:07,  2.29it/s]

read_audio_data
read_audio_data: complete, read  0 chunks.
analyze_recording 946266.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 946265.mp3
read_audio_data
read_audio_data: complete, read  0 chunks.
analyze_recording 946264.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 946263.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 837769.mp3

 25%|██▌       | 188/751 [04:20<03:45,  2.50it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 799805.mp3

 25%|██▌       | 189/751 [04:21<05:15,  1.78it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 743171.mp3

 25%|██▌       | 190/751 [04:22<05:17,  1.76it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 664437.mp3

 25%|██▌       | 191/751 [04:22<04:54,  1.90it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 549443.mp3

 26%|██▌       | 192/751 [04:23<04:21,  2.14it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 533160.mp3

 26%|██▌       | 193/751 [04:23<04:30,  2.06it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 438173.mp3

 26%|██▌       | 195/751 [04:24<04:35,  2.02it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 433380.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 428288.mp3
read_audio_data

 26%|██▌       | 197/751 [04:25<03:16,  2.82it/s]

read_audio_data: complete, read  3 chunks.
analyze_recording 360660.mp3
read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 335018.mp3

 26%|██▋       | 198/751 [04:26<04:50,  1.91it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 316131.mp3

 26%|██▋       | 199/751 [04:27<05:27,  1.69it/s]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 315080.mp3

 27%|██▋       | 200/751 [04:28<08:26,  1.09it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 299425.mp3

 27%|██▋       | 201/751 [04:29<07:22,  1.24it/s]

read_audio_data
read_audio_data: complete, read  35 chunks.
analyze_recording 245325.mp3

 27%|██▋       | 202/751 [04:31<10:32,  1.15s/it]

read_audio_data
read_audio_data: complete, read  22 chunks.
analyze_recording 245127.mp3

 27%|██▋       | 203/751 [04:32<10:46,  1.18s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 240116.mp3

 27%|██▋       | 204/751 [04:33<11:07,  1.22s/it]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 163746.mp3

 27%|██▋       | 205/751 [04:35<13:08,  1.44s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 163745.mp3

 28%|██▊       | 207/751 [04:36<07:26,  1.22it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 156278.mp3
read_audio_data

 28%|██▊       | 208/751 [04:36<05:52,  1.54it/s]

read_audio_data: complete, read  3 chunks.
analyze_recording 93770.mp3
read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 36849.mp3

 28%|██▊       | 209/751 [04:37<06:33,  1.38it/s]

read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording 1035875.mp3

 28%|██▊       | 210/751 [04:39<10:25,  1.16s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 841638.mp3

 28%|██▊       | 211/751 [04:40<08:27,  1.06it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 529586.mp3

 28%|██▊       | 212/751 [04:40<07:03,  1.27it/s]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 529585.mp3

 28%|██▊       | 213/751 [04:42<10:35,  1.18s/it]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 343255.mp3

 28%|██▊       | 214/751 [04:43<10:57,  1.22s/it]

read_audio_data
read_audio_data: complete, read  39 chunks.
analyze_recording 340081.mp3

 29%|██▊       | 215/751 [04:47<16:41,  1.87s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 320171.mp3

 29%|██▉       | 216/751 [04:47<13:16,  1.49s/it]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 244931.mp3

 29%|██▉       | 217/751 [04:49<12:35,  1.41s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 202849.mp3

 29%|██▉       | 218/751 [04:50<12:25,  1.40s/it]

read_audio_data
read_audio_data: complete, read  39 chunks.
analyze_recording 156379.mp3

 29%|██▉       | 219/751 [04:53<17:32,  1.98s/it]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 155834.mp3

 29%|██▉       | 220/751 [04:55<15:43,  1.78s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 155784.mp3

 29%|██▉       | 221/751 [04:55<11:38,  1.32s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 106254.mp3

 30%|██▉       | 222/751 [04:55<09:02,  1.03s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 97532.mp3

 30%|██▉       | 223/751 [04:56<07:53,  1.11it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 96253.mp3

 30%|██▉       | 224/751 [04:57<08:19,  1.06it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 93285.mp3

 30%|██▉       | 225/751 [04:58<08:34,  1.02it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 549995.mp3

 30%|███       | 227/751 [04:58<05:07,  1.70it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 433515.mp3
read_audio_data

 30%|███       | 228/751 [04:59<04:13,  2.06it/s]

read_audio_data: complete, read  3 chunks.
analyze_recording 97520.mp3
read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 24097.mp3

 30%|███       | 229/751 [04:59<04:57,  1.75it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 14594.mp3

 31%|███       | 230/751 [05:01<06:43,  1.29it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 528029.mp3

 31%|███       | 231/751 [05:02<06:48,  1.27it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 523326.mp3

 31%|███       | 233/751 [05:02<04:34,  1.89it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 1086722.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 1083717.mp3

 31%|███       | 234/751 [05:05<10:45,  1.25s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 1066284.mp3

 31%|███▏      | 235/751 [05:06<09:20,  1.09s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 985616.mp3

 31%|███▏      | 236/751 [05:06<07:08,  1.20it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 983138.mp3

 32%|███▏      | 237/751 [05:06<05:44,  1.49it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 956731.mp3

 32%|███▏      | 238/751 [05:07<06:19,  1.35it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 911203.mp3

 32%|███▏      | 239/751 [05:08<05:06,  1.67it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 881658.mp3

 32%|███▏      | 240/751 [05:08<04:50,  1.76it/s]

read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording 842648.mp3

 32%|███▏      | 241/751 [05:11<09:59,  1.18s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 829105.mp3

 32%|███▏      | 242/751 [05:11<08:35,  1.01s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 818069.mp3

 32%|███▏      | 243/751 [05:12<07:25,  1.14it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 795742.mp3

 32%|███▏      | 244/751 [05:13<08:37,  1.02s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 795740.mp3

 33%|███▎      | 245/751 [05:14<08:03,  1.05it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 771684.mp3

 33%|███▎      | 246/751 [05:15<07:36,  1.11it/s]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 769059.mp3

 33%|███▎      | 247/751 [05:16<09:46,  1.16s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 754061.mp3

 33%|███▎      | 249/751 [05:18<06:53,  1.21it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 745825.mp3
read_audio_data
read_audio_data: complete, read  29 chunks.
analyze_recording 742295.mp3

 33%|███▎      | 250/751 [05:19<08:52,  1.06s/it]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 737969.mp3

 33%|███▎      | 251/751 [05:20<08:32,  1.03s/it]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 737968.mp3

 34%|███▎      | 252/751 [05:21<07:50,  1.06it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 706525.mp3

 34%|███▎      | 253/751 [05:21<06:22,  1.30it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 706379.mp3

 34%|███▍      | 254/751 [05:22<05:18,  1.56it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 706374.mp3

 34%|███▍      | 255/751 [05:22<04:36,  1.79it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 693970.mp3

 34%|███▍      | 256/751 [05:22<04:12,  1.96it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 693969.mp3

 34%|███▍      | 257/751 [05:23<04:20,  1.90it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 693968.mp3

 34%|███▍      | 258/751 [05:23<03:53,  2.11it/s]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 660375.mp3

 34%|███▍      | 259/751 [05:25<06:10,  1.33it/s]

read_audio_data
read_audio_data: complete, read  26 chunks.
analyze_recording 649653.mp3

 35%|███▍      | 260/751 [05:26<07:38,  1.07it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 617981.mp3

 35%|███▍      | 261/751 [05:26<05:58,  1.37it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 589632.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 589631.mp3

 35%|███▌      | 263/751 [05:27<04:10,  1.95it/s]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 582909.mp3

 35%|███▌      | 264/751 [05:28<05:15,  1.54it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 581784.mp3

 35%|███▌      | 265/751 [05:28<04:56,  1.64it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 567472.mp3
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 567467.mp3

 36%|███▌      | 267/751 [05:29<04:26,  1.82it/s]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 562853.mp3

 36%|███▌      | 268/751 [05:30<05:08,  1.57it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 562327.mp3

 36%|███▌      | 269/751 [05:31<05:53,  1.36it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 558286.mp3

 36%|███▌      | 270/751 [05:32<04:55,  1.63it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 542500.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 518659.mp3

 36%|███▌      | 272/751 [05:33<05:02,  1.58it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 518258.mp3

 36%|███▋      | 273/751 [05:34<06:23,  1.25it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 516268.mp3

 36%|███▋      | 274/751 [05:35<05:42,  1.39it/s]

read_audio_data
read_audio_data: complete, read  54 chunks.
analyze_recording 516265.mp3

 37%|███▋      | 275/751 [05:39<14:06,  1.78s/it]

read_audio_data
read_audio_data: complete, read  20 chunks.
analyze_recording 508134.mp3

 37%|███▋      | 276/751 [05:41<14:07,  1.79s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 492288.mp3

 37%|███▋      | 277/751 [05:42<11:41,  1.48s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 465250.mp3

 37%|███▋      | 278/751 [05:43<09:46,  1.24s/it]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 446944.mp3
read_audio_data
read_audio_data: complete, read  36 chunks.
analyze_recording 445659.mp3

 37%|███▋      | 280/751 [05:46<11:15,  1.43s/it]

read_audio_data
read_audio_data: complete, read  39 chunks.
analyze_recording 432833.mp3

 37%|███▋      | 281/751 [05:48<12:18,  1.57s/it]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 424588.mp3

 38%|███▊      | 282/751 [05:49<10:50,  1.39s/it]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 423690.mp3

 38%|███▊      | 283/751 [05:50<10:29,  1.34s/it]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 423498.mp3

 38%|███▊      | 284/751 [05:51<10:15,  1.32s/it]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 423497.mp3

 38%|███▊      | 285/751 [05:53<10:33,  1.36s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 389896.mp3

 38%|███▊      | 286/751 [05:53<08:59,  1.16s/it]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 380282.mp3

 38%|███▊      | 287/751 [05:55<08:57,  1.16s/it]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 376473.mp3

 38%|███▊      | 288/751 [05:56<08:35,  1.11s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 373215.mp3

 38%|███▊      | 289/751 [05:56<06:58,  1.10it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 345881.mp3

 39%|███▊      | 290/751 [05:56<05:31,  1.39it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 344379.mp3

 39%|███▊      | 291/751 [05:58<06:47,  1.13it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 318704.mp3

 39%|███▉      | 292/751 [05:58<06:53,  1.11it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 302286.mp3

 39%|███▉      | 293/751 [05:59<05:34,  1.37it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 301004.mp3

 39%|███▉      | 294/751 [05:59<04:31,  1.69it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 299677.mp3

 39%|███▉      | 295/751 [06:00<04:50,  1.57it/s]

read_audio_data
read_audio_data: complete, read  42 chunks.
analyze_recording 241314.mp3

 39%|███▉      | 296/751 [06:02<08:49,  1.16s/it]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 241291.mp3

 40%|███▉      | 297/751 [06:04<09:08,  1.21s/it]

read_audio_data
read_audio_data: complete, read  42 chunks.
analyze_recording 241252.mp3

 40%|███▉      | 298/751 [06:06<11:36,  1.54s/it]

read_audio_data
read_audio_data: complete, read  63 chunks.
analyze_recording 240065.mp3

 40%|███▉      | 299/751 [06:11<19:30,  2.59s/it]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 236279.mp3

 40%|███▉      | 300/751 [06:13<17:23,  2.31s/it]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 236278.mp3

 40%|████      | 301/751 [06:14<14:30,  1.93s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 211069.mp3

 40%|████      | 302/751 [06:14<11:37,  1.55s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 154201.mp3

 40%|████      | 303/751 [06:15<09:16,  1.24s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 146411.mp3

 40%|████      | 304/751 [06:15<07:55,  1.06s/it]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 128185.mp3

 41%|████      | 305/751 [06:17<08:54,  1.20s/it]

read_audio_data
read_audio_data: complete, read  29 chunks.
analyze_recording 104827.mp3

 41%|████      | 306/751 [06:18<09:21,  1.26s/it]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 101564.mp3

 41%|████      | 307/751 [06:20<10:12,  1.38s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 101408.mp3

 41%|████      | 308/751 [06:21<09:12,  1.25s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 101407.mp3

 41%|████      | 309/751 [06:22<07:57,  1.08s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 101406.mp3

 41%|████▏     | 310/751 [06:22<06:26,  1.14it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 101405.mp3

 41%|████▏     | 311/751 [06:23<06:13,  1.18it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 96389.mp3

 42%|████▏     | 312/751 [06:24<06:55,  1.06it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 59680.mp3

 42%|████▏     | 313/751 [06:25<06:23,  1.14it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 59599.mp3

 42%|████▏     | 314/751 [06:25<05:31,  1.32it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 59598.mp3

 42%|████▏     | 315/751 [06:26<04:41,  1.55it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 54492.mp3

 42%|████▏     | 316/751 [06:27<05:30,  1.31it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 53008.mp3

 42%|████▏     | 317/751 [06:28<06:11,  1.17it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 53007.mp3

 42%|████▏     | 318/751 [06:29<06:47,  1.06it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 45519.mp3

 42%|████▏     | 319/751 [06:29<05:59,  1.20it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 18272.mp3

 43%|████▎     | 320/751 [06:30<05:37,  1.28it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 12419.mp3

 43%|████▎     | 321/751 [06:31<04:52,  1.47it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 12269.mp3

 43%|████▎     | 322/751 [06:31<05:24,  1.32it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 11293.mp3

 43%|████▎     | 323/751 [06:32<04:48,  1.49it/s]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 1049463.mp3

 43%|████▎     | 324/751 [06:33<06:37,  1.07it/s]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 1047132.mp3

 43%|████▎     | 325/751 [06:35<08:38,  1.22s/it]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 1047131.mp3

 43%|████▎     | 326/751 [06:36<08:16,  1.17s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 1035184.mp3

 44%|████▎     | 327/751 [06:37<07:12,  1.02s/it]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 1031726.mp3

 44%|████▎     | 328/751 [06:39<09:22,  1.33s/it]

read_audio_data
read_audio_data: complete, read  22 chunks.
analyze_recording 1005091.mp3

 44%|████▍     | 329/751 [06:40<08:52,  1.26s/it]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 993282.mp3

 44%|████▍     | 330/751 [06:41<08:35,  1.22s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 537304.mp3

 44%|████▍     | 331/751 [06:42<07:16,  1.04s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 534023.mp3

 44%|████▍     | 332/751 [06:43<07:13,  1.03s/it]

read_audio_data
read_audio_data: complete, read  22 chunks.
analyze_recording 534022.mp3

 44%|████▍     | 333/751 [06:45<08:53,  1.28s/it]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 533982.mp3

 44%|████▍     | 334/751 [06:46<09:24,  1.35s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 525024.mp3

 45%|████▍     | 335/751 [06:48<09:22,  1.35s/it]

read_audio_data
read_audio_data: complete, read  34 chunks.
analyze_recording 389348.mp3

 45%|████▍     | 336/751 [06:51<12:29,  1.81s/it]Warning: Xing stream size off by more than 1%, fuzzy seeking may be even more fuzzy than by design!

read_audio_data
read_audio_data: complete, read  0 chunks.
analyze_recording 328012.mp3
read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 960832.mp3

 45%|████▌     | 338/751 [06:51<07:24,  1.08s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 944467.mp3

 45%|████▌     | 339/751 [06:52<07:28,  1.09s/it]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 944466.mp3

 45%|████▌     | 340/751 [06:54<09:38,  1.41s/it]

read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording 844279.mp3

 45%|████▌     | 341/751 [06:56<10:15,  1.50s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 825534.mp3

 46%|████▌     | 342/751 [06:57<08:38,  1.27s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 742383.mp3

 46%|████▌     | 343/751 [06:57<06:33,  1.04it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 683932.mp3

 46%|████▌     | 344/751 [06:58<06:14,  1.09it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 636053.mp3

 46%|████▌     | 345/751 [06:58<05:09,  1.31it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 560167.mp3

 46%|████▌     | 347/751 [06:59<03:40,  1.83it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 543737.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 530782.mp3

 46%|████▋     | 348/751 [07:00<05:21,  1.25it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 457445.mp3

 47%|████▋     | 350/751 [07:01<03:21,  1.99it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 454496.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 445037.mp3

 47%|████▋     | 351/751 [07:02<04:26,  1.50it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 423704.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 320248.mp3

 47%|████▋     | 353/751 [07:02<02:52,  2.31it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 320170.mp3

 47%|████▋     | 354/751 [07:03<03:38,  1.82it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 273558.mp3

 47%|████▋     | 355/751 [07:04<04:14,  1.56it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 236254.mp3

 47%|████▋     | 356/751 [07:04<03:34,  1.84it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 167035.mp3

 48%|████▊     | 357/751 [07:05<03:22,  1.95it/s]

read_audio_data
read_audio_data: complete, read  20 chunks.
analyze_recording 163753.mp3

 48%|████▊     | 358/751 [07:07<05:51,  1.12it/s]Warning: Xing stream size off by more than 1%, fuzzy seeking may be even more fuzzy than by design!

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 163750.mp3
read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 131763.mp3

 48%|████▊     | 360/751 [07:09<06:16,  1.04it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 91895.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 1037803.mp3

 48%|████▊     | 362/751 [07:10<05:12,  1.25it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 1037802.mp3

 48%|████▊     | 363/751 [07:10<04:40,  1.38it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 1031812.mp3

 48%|████▊     | 364/751 [07:11<05:22,  1.20it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 975737.mp3

 49%|████▊     | 365/751 [07:12<05:21,  1.20it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 974448.mp3

 49%|████▉     | 368/751 [07:13<02:49,  2.25it/s]

read_audio_data
read_audio_data: complete, read  0 chunks.
analyze_recording 946282.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 946281.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 946280.mp3
read_audio_data
read_audio_data: complete, read  0 chunks.
analyze_recording 946279.mp3
read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 843650.mp3

 49%|████▉     | 371/751 [07:14<02:46,  2.28it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 799803.mp3

 50%|████▉     | 372/751 [07:14<02:33,  2.47it/s]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 799784.mp3

 50%|████▉     | 373/751 [07:16<04:42,  1.34it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 693950.mp3

 50%|████▉     | 374/751 [07:17<04:07,  1.52it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 664443.mp3

 50%|████▉     | 375/751 [07:17<04:05,  1.53it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 609459.mp3

 50%|█████     | 376/751 [07:18<04:28,  1.39it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 542114.mp3

 50%|█████     | 377/751 [07:19<04:31,  1.38it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 540100.mp3

 50%|█████     | 378/751 [07:20<04:23,  1.42it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 532999.mp3

 50%|█████     | 379/751 [07:21<05:01,  1.23it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 532998.mp3

 51%|█████     | 380/751 [07:22<05:16,  1.17it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 532997.mp3

 51%|█████     | 381/751 [07:22<04:10,  1.48it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 532996.mp3

 51%|█████     | 382/751 [07:22<03:48,  1.61it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 532995.mp3

 51%|█████     | 383/751 [07:23<03:29,  1.76it/s]

read_audio_data
read_audio_data: complete, read  25 chunks.
analyze_recording 532994.mp3

 51%|█████     | 384/751 [07:25<06:25,  1.05s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 532549.mp3

 51%|█████▏    | 385/751 [07:25<05:00,  1.22it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 524130.mp3

 51%|█████▏    | 386/751 [07:26<04:28,  1.36it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 454487.mp3

 52%|█████▏    | 387/751 [07:26<03:32,  1.71it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 433172.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 429837.mp3

 52%|█████▏    | 389/751 [07:26<02:18,  2.62it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 361487.mp3

 52%|█████▏    | 390/751 [07:27<02:25,  2.48it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 357282.mp3

 52%|█████▏    | 391/751 [07:28<03:11,  1.88it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 354170.mp3

 52%|█████▏    | 392/751 [07:28<03:00,  1.99it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 318776.mp3

 52%|█████▏    | 393/751 [07:30<04:25,  1.35it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 296755.mp3

 53%|█████▎    | 395/751 [07:30<02:59,  1.99it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 273672.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 273557.mp3

 53%|█████▎    | 396/751 [07:31<04:14,  1.40it/s]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 273374.mp3

 53%|█████▎    | 397/751 [07:33<05:42,  1.03it/s]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 245144.mp3

 53%|█████▎    | 398/751 [07:34<05:51,  1.00it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 163744.mp3

 53%|█████▎    | 399/751 [07:34<04:45,  1.23it/s]

read_audio_data
read_audio_data: complete, read  25 chunks.
analyze_recording 148137.mp3

 53%|█████▎    | 400/751 [07:37<07:06,  1.21s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 131753.mp3

 53%|█████▎    | 401/751 [07:37<05:24,  1.08it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 127055.mp3

 54%|█████▎    | 402/751 [07:38<05:51,  1.01s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 105657.mp3

 54%|█████▎    | 403/751 [07:38<04:31,  1.28it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 54542.mp3

 54%|█████▍    | 404/751 [07:39<04:07,  1.40it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 1084865.mp3

 54%|█████▍    | 405/751 [07:40<04:56,  1.17it/s]

read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording 1000789.mp3

 54%|█████▍    | 406/751 [07:42<07:09,  1.24s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 839870.mp3

 54%|█████▍    | 408/751 [07:43<04:28,  1.28it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 156225.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 155967.mp3

 54%|█████▍    | 409/751 [07:44<04:08,  1.38it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 108988.mp3

 55%|█████▍    | 410/751 [07:44<04:24,  1.29it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 106328.mp3

 55%|█████▍    | 411/751 [07:45<04:24,  1.29it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 97561.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 54985.mp3

 55%|█████▌    | 414/751 [07:46<02:19,  2.42it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 841639.mp3
read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 108989.mp3

 55%|█████▌    | 415/751 [07:47<03:13,  1.74it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 97523.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 943098.mp3

 56%|█████▌    | 417/751 [07:47<02:26,  2.27it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 698051.mp3

 56%|█████▌    | 418/751 [07:49<03:35,  1.54it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 656171.mp3

 56%|█████▌    | 419/751 [07:49<03:32,  1.56it/s]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 292292.mp3

 56%|█████▌    | 420/751 [07:51<05:24,  1.02it/s]

read_audio_data
read_audio_data: complete, read  37 chunks.
analyze_recording 129731.mp3

 56%|█████▌    | 421/751 [07:54<08:34,  1.56s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 128192.mp3

 56%|█████▌    | 422/751 [07:55<07:16,  1.33s/it]

read_audio_data
read_audio_data: complete, read  20 chunks.
analyze_recording 103481.mp3

 56%|█████▋    | 423/751 [07:56<06:44,  1.23s/it]

read_audio_data
read_audio_data: complete, read  41 chunks.
analyze_recording 844277.mp3

 56%|█████▋    | 424/751 [07:58<07:56,  1.46s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 837573.mp3

 57%|█████▋    | 425/751 [07:59<06:55,  1.27s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 656175.mp3

 57%|█████▋    | 426/751 [07:59<05:23,  1.01it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 656174.mp3

 57%|█████▋    | 427/751 [07:59<04:17,  1.26it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 656172.mp3

 57%|█████▋    | 428/751 [08:00<03:39,  1.47it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 532440.mp3

 57%|█████▋    | 429/751 [08:01<04:10,  1.29it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 446429.mp3

 57%|█████▋    | 430/751 [08:01<03:55,  1.36it/s]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 415213.mp3

 57%|█████▋    | 431/751 [08:03<05:12,  1.02it/s]

read_audio_data
read_audio_data: complete, read  26 chunks.
analyze_recording 303953.mp3

 58%|█████▊    | 432/751 [08:05<06:57,  1.31s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 299426.mp3

 58%|█████▊    | 433/751 [08:05<05:24,  1.02s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 245029.mp3

 58%|█████▊    | 434/751 [08:06<04:56,  1.07it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 181554.mp3

 58%|█████▊    | 435/751 [08:07<04:15,  1.24it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 181553.mp3

 58%|█████▊    | 436/751 [08:08<04:27,  1.18it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 95957.mp3

 58%|█████▊    | 437/751 [08:09<04:42,  1.11it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 838018.mp3

 58%|█████▊    | 438/751 [08:10<05:00,  1.04it/s]

read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording 357277.mp3

 58%|█████▊    | 439/751 [08:12<07:08,  1.37s/it]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 93534.mp3

 59%|█████▊    | 440/751 [08:14<07:28,  1.44s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 93030.mp3

 59%|█████▉    | 442/751 [08:14<04:22,  1.18it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 53432.mp3
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 53384.mp3

 59%|█████▉    | 443/751 [08:15<04:18,  1.19it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 52956.mp3

 59%|█████▉    | 444/751 [08:16<03:59,  1.28it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 43798.mp3

 59%|█████▉    | 445/751 [08:17<04:09,  1.23it/s]

read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording 36841.mp3

 59%|█████▉    | 446/751 [08:19<06:20,  1.25s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 18270.mp3

 60%|█████▉    | 447/751 [08:19<05:01,  1.01it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 260141.mp3
read_audio_data
read_audio_data: complete, read  0 chunks.
analyze_recording 260140.mp3
read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 533987.mp3

 60%|█████▉    | 450/751 [08:21<03:46,  1.33it/s]

read_audio_data
read_audio_data: complete, read  44 chunks.
analyze_recording 525762.mp3

 60%|██████    | 451/751 [08:25<06:53,  1.38s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 525023.mp3

 60%|██████    | 452/751 [08:25<06:03,  1.22s/it]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 525022.mp3

 60%|██████    | 453/751 [08:27<06:00,  1.21s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 525021.mp3

 60%|██████    | 454/751 [08:27<04:53,  1.01it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 525020.mp3

 61%|██████    | 455/751 [08:28<04:55,  1.00it/s]

read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording 525019.mp3

 61%|██████    | 456/751 [08:31<07:13,  1.47s/it]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 525018.mp3

 61%|██████    | 457/751 [08:32<07:07,  1.45s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 1083970.mp3

 61%|██████    | 458/751 [08:35<09:03,  1.85s/it]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 963260.mp3

 61%|██████    | 459/751 [08:36<07:24,  1.52s/it]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 960809.mp3

 61%|██████▏   | 460/751 [08:37<06:32,  1.35s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 958210.mp3

 61%|██████▏   | 461/751 [08:37<05:30,  1.14s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 922966.mp3

 62%|██████▏   | 462/751 [08:38<04:24,  1.09it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 919202.mp3

 62%|██████▏   | 463/751 [08:39<04:37,  1.04it/s]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 905410.mp3

 62%|██████▏   | 464/751 [08:40<05:20,  1.12s/it]

read_audio_data
read_audio_data: complete, read  29 chunks.
analyze_recording 902970.mp3

 62%|██████▏   | 465/751 [08:42<06:56,  1.46s/it]

read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording 844132.mp3

 62%|██████▏   | 466/751 [08:45<08:02,  1.69s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 842006.mp3

 62%|██████▏   | 467/751 [08:46<07:02,  1.49s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 816680.mp3

 62%|██████▏   | 469/751 [08:46<04:08,  1.13it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 812834.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 811608.mp3

 63%|██████▎   | 470/751 [08:47<03:26,  1.36it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 801697.mp3

 63%|██████▎   | 471/751 [08:48<03:46,  1.23it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 742391.mp3

 63%|██████▎   | 472/751 [08:48<03:17,  1.41it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 742381.mp3

 63%|██████▎   | 473/751 [08:49<03:09,  1.46it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 742380.mp3

 63%|██████▎   | 474/751 [08:50<03:13,  1.43it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 742339.mp3

 63%|██████▎   | 475/751 [08:50<03:25,  1.34it/s]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 742338.mp3

 63%|██████▎   | 476/751 [08:51<03:41,  1.24it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 742337.mp3

 64%|██████▎   | 477/751 [08:52<03:24,  1.34it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 742294.mp3

 64%|██████▎   | 478/751 [08:52<03:00,  1.51it/s]

read_audio_data
read_audio_data: complete, read  42 chunks.
analyze_recording 742293.mp3

 64%|██████▍   | 479/751 [08:55<05:02,  1.11s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 742292.mp3

 64%|██████▍   | 480/751 [08:55<03:57,  1.14it/s]

read_audio_data
read_audio_data: complete, read  26 chunks.
analyze_recording 705153.mp3

 64%|██████▍   | 481/751 [08:56<04:32,  1.01s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 693928.mp3

 64%|██████▍   | 482/751 [08:57<03:40,  1.22it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 693927.mp3

 64%|██████▍   | 483/751 [08:57<02:54,  1.53it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 693925.mp3

 64%|██████▍   | 484/751 [08:57<02:36,  1.71it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 690998.mp3

 65%|██████▍   | 485/751 [08:58<02:21,  1.88it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 690997.mp3

 65%|██████▍   | 486/751 [08:58<02:26,  1.81it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 690994.mp3

 65%|██████▍   | 487/751 [08:59<02:32,  1.73it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 660132.mp3

 65%|██████▍   | 488/751 [09:00<03:31,  1.24it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 622474.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 622438.mp3

 65%|██████▌   | 490/751 [09:01<02:33,  1.70it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 622436.mp3

 65%|██████▌   | 491/751 [09:01<02:11,  1.98it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 601968.mp3

 66%|██████▌   | 492/751 [09:02<02:09,  2.01it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 589898.mp3

 66%|██████▌   | 493/751 [09:02<01:51,  2.31it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 586689.mp3

 66%|██████▌   | 494/751 [09:02<01:38,  2.62it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 585338.mp3

 66%|██████▌   | 495/751 [09:03<02:31,  1.69it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 585313.mp3

 66%|██████▌   | 496/751 [09:04<02:19,  1.83it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 573807.mp3

 66%|██████▌   | 497/751 [09:04<02:03,  2.06it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 571649.mp3

 66%|██████▋   | 498/751 [09:05<02:03,  2.05it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 562333.mp3

 66%|██████▋   | 499/751 [09:05<02:01,  2.08it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 559631.mp3

 67%|██████▋   | 500/751 [09:06<02:14,  1.86it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 559629.mp3

 67%|██████▋   | 502/751 [09:06<01:36,  2.59it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 554229.mp3
read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 549491.mp3

 67%|██████▋   | 503/751 [09:07<02:16,  1.82it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 542241.mp3

 67%|██████▋   | 504/751 [09:08<02:47,  1.47it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 539380.mp3

 67%|██████▋   | 505/751 [09:08<02:15,  1.82it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 497632.mp3

 67%|██████▋   | 506/751 [09:09<01:53,  2.16it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 483591.mp3

 68%|██████▊   | 507/751 [09:10<02:33,  1.59it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 455162.mp3

 68%|██████▊   | 508/751 [09:10<02:33,  1.58it/s]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 442581.mp3

 68%|██████▊   | 509/751 [09:12<03:44,  1.08it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 433184.mp3

 68%|██████▊   | 510/751 [09:13<04:03,  1.01s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 424026.mp3

 68%|██████▊   | 511/751 [09:14<03:32,  1.13it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 414148.mp3

 68%|██████▊   | 513/751 [09:14<02:16,  1.74it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 382495.mp3
read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 362360.mp3

 68%|██████▊   | 514/751 [09:15<02:32,  1.56it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 362359.mp3

 69%|██████▊   | 515/751 [09:16<02:32,  1.55it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 360376.mp3

 69%|██████▊   | 516/751 [09:17<02:39,  1.47it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 357866.mp3

 69%|██████▉   | 517/751 [09:18<03:27,  1.13it/s]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 346207.mp3

 69%|██████▉   | 518/751 [09:19<04:03,  1.04s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 344337.mp3

 69%|██████▉   | 519/751 [09:20<03:45,  1.03it/s]

read_audio_data
read_audio_data: complete, read  52 chunks.
analyze_recording 335020.mp3

 69%|██████▉   | 520/751 [09:23<05:50,  1.52s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 335013.mp3

 69%|██████▉   | 521/751 [09:24<05:03,  1.32s/it]Warning: Xing stream size off by more than 1%, fuzzy seeking may be even more fuzzy than by design!

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 326992.mp3
read_audio_data
read_audio_data: complete, read  70 chunks.
analyze_recording 320180.mp3

 70%|██████▉   | 523/751 [09:28<06:01,  1.59s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 318702.mp3

 70%|██████▉   | 524/751 [09:28<04:55,  1.30s/it]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 318701.mp3

 70%|██████▉   | 525/751 [09:29<04:47,  1.27s/it]

read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording 317810.mp3

 70%|███████   | 526/751 [09:31<05:49,  1.56s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 312410.mp3

 70%|███████   | 527/751 [09:32<04:33,  1.22s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 302234.mp3

 70%|███████   | 528/751 [09:32<03:30,  1.06it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 302233.mp3

 70%|███████   | 529/751 [09:32<02:50,  1.30it/s]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 298077.mp3

 71%|███████   | 530/751 [09:34<03:59,  1.08s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 296757.mp3

 71%|███████   | 531/751 [09:35<03:12,  1.14it/s]

read_audio_data
read_audio_data: complete, read  52 chunks.
analyze_recording 289423.mp3

 71%|███████   | 532/751 [09:39<06:46,  1.86s/it]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 282406.mp3

 71%|███████   | 533/751 [09:40<06:02,  1.66s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 250899.mp3

 71%|███████   | 534/751 [09:41<05:12,  1.44s/it]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 236222.mp3

 71%|███████   | 535/751 [09:42<04:58,  1.38s/it]

read_audio_data
read_audio_data: complete, read  20 chunks.
analyze_recording 236221.mp3

 71%|███████▏  | 536/751 [09:44<05:13,  1.46s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 236219.mp3

 72%|███████▏  | 537/751 [09:44<04:15,  1.19s/it]

read_audio_data
read_audio_data: complete, read  31 chunks.
analyze_recording 154685.mp3

 72%|███████▏  | 538/751 [09:47<05:40,  1.60s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 147537.mp3

 72%|███████▏  | 539/751 [09:47<04:15,  1.20s/it]

read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording 127867.mp3

 72%|███████▏  | 540/751 [09:50<05:46,  1.64s/it]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 104642.mp3

 72%|███████▏  | 541/751 [09:51<05:02,  1.44s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 103480.mp3

 72%|███████▏  | 542/751 [09:51<04:00,  1.15s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 101813.mp3

 72%|███████▏  | 543/751 [09:52<03:26,  1.01it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 101570.mp3

 72%|███████▏  | 544/751 [09:52<02:55,  1.18it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 101563.mp3

 73%|███████▎  | 545/751 [09:54<03:16,  1.05it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 86324.mp3

 73%|███████▎  | 546/751 [09:54<02:56,  1.16it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 45541.mp3

 73%|███████▎  | 547/751 [09:55<02:23,  1.43it/s]

read_audio_data
read_audio_data: complete, read  26 chunks.
analyze_recording 28617.mp3

 73%|███████▎  | 548/751 [09:57<03:44,  1.11s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 1074995.mp3

 73%|███████▎  | 549/751 [09:59<04:28,  1.33s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 1040013.mp3

 73%|███████▎  | 550/751 [09:59<03:57,  1.18s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 1040012.mp3

 73%|███████▎  | 551/751 [10:00<03:04,  1.08it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 614559.mp3

 74%|███████▎  | 552/751 [10:00<02:24,  1.37it/s]

read_audio_data
read_audio_data: complete, read  26 chunks.
analyze_recording 518225.mp3

 74%|███████▎  | 553/751 [10:02<03:49,  1.16s/it]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 386463.mp3

 74%|███████▍  | 555/751 [10:03<02:17,  1.43it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 377900.mp3
read_audio_data
read_audio_data: complete, read  51 chunks.
analyze_recording 361196.mp3

 74%|███████▍  | 557/751 [10:07<04:13,  1.31s/it]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 240064.mp3
read_audio_data

 74%|███████▍  | 558/751 [10:07<03:07,  1.03it/s]

read_audio_data: complete, read  2 chunks.
analyze_recording 213482.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 148298.mp3

 74%|███████▍  | 559/751 [10:08<03:09,  1.02it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 127960.mp3

 75%|███████▍  | 560/751 [10:09<03:10,  1.00it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 127226.mp3

 75%|███████▍  | 561/751 [10:10<02:27,  1.29it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 52715.mp3

 75%|███████▍  | 562/751 [10:11<02:33,  1.23it/s]

read_audio_data
read_audio_data: complete, read  20 chunks.
analyze_recording 36853.mp3

 75%|███████▍  | 563/751 [10:12<03:19,  1.06s/it]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 10772.mp3

 75%|███████▌  | 564/751 [10:13<02:59,  1.04it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 1140423.mp3

 75%|███████▌  | 565/751 [10:13<02:27,  1.26it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 1018436.mp3

 75%|███████▌  | 566/751 [10:14<02:18,  1.33it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 1005797.mp3

 75%|███████▌  | 567/751 [10:15<02:34,  1.19it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 996133.mp3

 76%|███████▌  | 568/751 [10:16<02:11,  1.40it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 995358.mp3

 76%|███████▌  | 569/751 [10:16<01:55,  1.57it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 995346.mp3

 76%|███████▌  | 570/751 [10:16<01:35,  1.90it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 986959.mp3

 76%|███████▌  | 572/751 [10:17<01:13,  2.45it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 986958.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 975752.mp3

 76%|███████▋  | 574/751 [10:18<01:04,  2.75it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 974246.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 974245.mp3

 77%|███████▋  | 575/751 [10:18<01:21,  2.17it/s]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 974237.mp3

 77%|███████▋  | 576/751 [10:19<01:45,  1.66it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 974208.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 946062.mp3

 77%|███████▋  | 578/751 [10:20<01:08,  2.54it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 946061.mp3

 77%|███████▋  | 579/751 [10:20<01:25,  2.01it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 912265.mp3

 77%|███████▋  | 580/751 [10:21<01:17,  2.20it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 820345.mp3

 77%|███████▋  | 581/751 [10:21<01:25,  2.00it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 747131.mp3

 77%|███████▋  | 582/751 [10:22<01:49,  1.55it/s]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 672031.mp3

 78%|███████▊  | 583/751 [10:24<02:58,  1.06s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 614560.mp3

 78%|███████▊  | 584/751 [10:25<02:55,  1.05s/it]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 607831.mp3

 78%|███████▊  | 585/751 [10:26<02:20,  1.18it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 577135.mp3

 78%|███████▊  | 586/751 [10:26<01:54,  1.44it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 532797.mp3

 78%|███████▊  | 587/751 [10:27<01:37,  1.69it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 523853.mp3

 78%|███████▊  | 588/751 [10:28<02:08,  1.27it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 523852.mp3

 78%|███████▊  | 589/751 [10:29<02:10,  1.24it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 523851.mp3

 79%|███████▊  | 590/751 [10:30<02:18,  1.16it/s]

read_audio_data
read_audio_data: complete, read  70 chunks.
analyze_recording 523849.mp3

 79%|███████▊  | 591/751 [10:35<06:12,  2.33s/it]

read_audio_data
read_audio_data: complete, read  71 chunks.
analyze_recording 523848.mp3

 79%|███████▉  | 592/751 [10:41<08:58,  3.39s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 523847.mp3

 79%|███████▉  | 593/751 [10:42<06:46,  2.57s/it]

read_audio_data
read_audio_data: complete, read  33 chunks.
analyze_recording 517921.mp3

 79%|███████▉  | 594/751 [10:45<06:51,  2.62s/it]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 517920.mp3

 79%|███████▉  | 595/751 [10:46<06:00,  2.31s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 456654.mp3

 79%|███████▉  | 596/751 [10:47<04:30,  1.74s/it]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 432603.mp3

 79%|███████▉  | 597/751 [10:48<03:49,  1.49s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 386462.mp3

 80%|███████▉  | 598/751 [10:48<03:06,  1.22s/it]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 326994.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 326979.mp3

 80%|███████▉  | 600/751 [10:49<02:12,  1.14it/s]

read_audio_data
read_audio_data: complete, read  20 chunks.
analyze_recording 320352.mp3

 80%|████████  | 601/751 [10:50<02:19,  1.08it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 267413.mp3

 80%|████████  | 602/751 [10:51<02:21,  1.06it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 244744.mp3

 80%|████████  | 603/751 [10:52<02:32,  1.03s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 235665.mp3

 80%|████████  | 604/751 [10:53<02:22,  1.03it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 152241.mp3

 81%|████████  | 605/751 [10:54<02:11,  1.11it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 148299.mp3

 81%|████████  | 606/751 [10:54<01:53,  1.28it/s]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 148220.mp3

 81%|████████  | 607/751 [10:56<02:25,  1.01s/it]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 148219.mp3

 81%|████████  | 608/751 [10:57<02:27,  1.03s/it]

read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording 131825.mp3

 81%|████████  | 609/751 [11:00<03:40,  1.55s/it]

read_audio_data
read_audio_data: complete, read  31 chunks.
analyze_recording 128189.mp3

 81%|████████  | 610/751 [11:03<04:25,  1.89s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 57256.mp3

 81%|████████▏ | 611/751 [11:03<03:23,  1.45s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 56449.mp3

 81%|████████▏ | 612/751 [11:03<02:35,  1.12s/it]

read_audio_data
read_audio_data: complete, read  0 chunks.
analyze_recording 958229.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 915108.mp3

 82%|████████▏ | 615/751 [11:04<01:21,  1.67it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 438407.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 379480.mp3

 82%|████████▏ | 616/751 [11:05<01:29,  1.50it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 353371.mp3

 82%|████████▏ | 617/751 [11:05<01:16,  1.74it/s]Warning: Xing stream size off by more than 1%, fuzzy seeking may be even more fuzzy than by design!

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 302309.mp3

 82%|████████▏ | 618/751 [11:06<01:30,  1.47it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 293802.mp3

 82%|████████▏ | 619/751 [11:07<01:16,  1.72it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 288825.mp3

 83%|████████▎ | 621/751 [11:07<01:00,  2.16it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 201027.mp3
read_audio_data

 83%|████████▎ | 622/751 [11:08<00:51,  2.49it/s]

read_audio_data: complete, read  3 chunks.
analyze_recording 86791.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 86790.mp3

 83%|████████▎ | 623/751 [11:08<00:56,  2.27it/s]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 73313.mp3

 83%|████████▎ | 624/751 [11:10<01:39,  1.28it/s]

read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording 38839.mp3

 83%|████████▎ | 625/751 [11:12<02:19,  1.11s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 37287.mp3

 83%|████████▎ | 627/751 [11:13<01:32,  1.33it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 549906.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 367226.mp3

 84%|████████▎ | 628/751 [11:14<01:48,  1.14it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 148250.mp3

 84%|████████▍ | 629/751 [11:15<01:52,  1.09it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 98900.mp3

 84%|████████▍ | 631/751 [11:15<01:06,  1.81it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 98899.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 693909.mp3

 84%|████████▍ | 632/751 [11:16<01:02,  1.91it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 577133.mp3

 84%|████████▍ | 633/751 [11:16<01:02,  1.88it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 576037.mp3

 84%|████████▍ | 634/751 [11:16<00:53,  2.19it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 544948.mp3

 85%|████████▍ | 635/751 [11:17<00:52,  2.23it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 543342.mp3

 85%|████████▍ | 637/751 [11:17<00:38,  2.94it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 539844.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 539843.mp3

 85%|████████▌ | 639/751 [11:18<00:34,  3.28it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 537981.mp3
read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 527993.mp3

 85%|████████▌ | 640/751 [11:19<00:54,  2.03it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 449494.mp3

 85%|████████▌ | 641/751 [11:20<00:58,  1.88it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 424719.mp3

 85%|████████▌ | 642/751 [11:20<00:51,  2.10it/s]

read_audio_data
read_audio_data: complete, read  44 chunks.
analyze_recording 365693.mp3

 86%|████████▌ | 643/751 [11:24<02:36,  1.45s/it]

read_audio_data
read_audio_data: complete, read  44 chunks.
analyze_recording 245423.mp3

 86%|████████▌ | 645/751 [11:26<02:10,  1.23s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 81825.mp3
read_audio_data

 86%|████████▌ | 646/751 [11:26<01:40,  1.05it/s]

read_audio_data: complete, read  4 chunks.
analyze_recording 1142791.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 975727.mp3

 86%|████████▌ | 647/751 [11:27<01:39,  1.05it/s]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 974052.mp3

 86%|████████▋ | 648/751 [11:28<01:38,  1.04it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 946268.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 857606.mp3

 87%|████████▋ | 650/751 [11:29<01:16,  1.32it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 834225.mp3

 87%|████████▋ | 651/751 [11:31<01:28,  1.13it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 790362.mp3

 87%|████████▋ | 652/751 [11:31<01:26,  1.14it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 719958.mp3

 87%|████████▋ | 653/751 [11:32<01:16,  1.28it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 577066.mp3

 87%|████████▋ | 654/751 [11:32<01:08,  1.42it/s]

read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording 454499.mp3

 87%|████████▋ | 655/751 [11:33<01:16,  1.25it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 432992.mp3
read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 370318.mp3

 88%|████████▊ | 658/751 [11:35<00:48,  1.92it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 360398.mp3
read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 319636.mp3

 88%|████████▊ | 659/751 [11:35<00:53,  1.72it/s]

read_audio_data
read_audio_data: complete, read  45 chunks.
analyze_recording 245148.mp3

 88%|████████▊ | 660/751 [11:38<01:36,  1.06s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 213479.mp3

 88%|████████▊ | 661/751 [11:38<01:15,  1.20it/s]

read_audio_data
read_audio_data: complete, read  102 chunks.
analyze_recording 130761.mp3

 88%|████████▊ | 662/751 [11:46<04:22,  2.95s/it]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 127974.mp3

 88%|████████▊ | 663/751 [11:48<03:55,  2.67s/it]

read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording 127973.mp3

 88%|████████▊ | 664/751 [11:49<03:10,  2.19s/it]

read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording 12266.mp3

 89%|████████▊ | 665/751 [11:51<02:49,  1.97s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 525435.mp3

 89%|████████▊ | 666/751 [11:52<02:34,  1.82s/it]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 454500.mp3

 89%|████████▉ | 667/751 [11:53<02:07,  1.52s/it]

read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording 454498.mp3

 89%|████████▉ | 668/751 [11:55<02:09,  1.56s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 454497.mp3

 89%|████████▉ | 669/751 [11:55<01:41,  1.23s/it]

read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording 340084.mp3

 89%|████████▉ | 670/751 [11:58<02:18,  1.71s/it]

read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording 340083.mp3

 89%|████████▉ | 671/751 [12:00<02:15,  1.70s/it]

read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording 340082.mp3

 89%|████████▉ | 672/751 [12:02<02:27,  1.86s/it]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 245551.mp3

 90%|████████▉ | 674/751 [12:03<01:34,  1.23s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 128400.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 122348.mp3

 90%|████████▉ | 675/751 [12:04<01:18,  1.03s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 36926.mp3

 90%|█████████ | 676/751 [12:04<01:01,  1.21it/s]

read_audio_data
read_audio_data: complete, read  39 chunks.
analyze_recording 319948.mp3

 90%|█████████ | 677/751 [12:07<01:55,  1.56s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 731341.mp3

 90%|█████████ | 678/751 [12:08<01:25,  1.17s/it]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 589640.mp3

 90%|█████████ | 679/751 [12:09<01:29,  1.24s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 589638.mp3

 91%|█████████ | 680/751 [12:09<01:08,  1.04it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 560204.mp3

 91%|█████████ | 681/751 [12:10<00:53,  1.32it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 560202.mp3

 91%|█████████ | 682/751 [12:10<00:41,  1.66it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 558248.mp3

 91%|█████████ | 683/751 [12:10<00:34,  1.99it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 454491.mp3

 91%|█████████ | 684/751 [12:10<00:27,  2.39it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 445081.mp3

 91%|█████████ | 685/751 [12:11<00:25,  2.57it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 353887.mp3

 91%|█████████▏| 686/751 [12:11<00:33,  1.96it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 343234.mp3

 91%|█████████▏| 687/751 [12:12<00:28,  2.27it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 317800.mp3

 92%|█████████▏| 688/751 [12:12<00:31,  1.97it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 312359.mp3

 92%|█████████▏| 689/751 [12:13<00:27,  2.23it/s]

read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording 310060.mp3

 92%|█████████▏| 690/751 [12:15<00:55,  1.11it/s]

read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording 148065.mp3

 92%|█████████▏| 691/751 [12:17<01:27,  1.46s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 139472.mp3

 92%|█████████▏| 692/751 [12:18<01:04,  1.09s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 115472.mp3

 92%|█████████▏| 693/751 [12:18<00:56,  1.03it/s]

read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording 1140065.mp3

 92%|█████████▏| 694/751 [12:20<01:00,  1.07s/it]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 1140062.mp3

 93%|█████████▎| 695/751 [12:20<00:53,  1.06it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 975731.mp3

 93%|█████████▎| 697/751 [12:21<00:34,  1.55it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 975730.mp3
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 960815.mp3

 93%|█████████▎| 698/751 [12:22<00:31,  1.66it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 827682.mp3

 93%|█████████▎| 699/751 [12:22<00:27,  1.87it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording 589641.mp3
read_audio_data

 93%|█████████▎| 701/751 [12:22<00:18,  2.69it/s]

read_audio_data: complete, read  3 chunks.
analyze_recording 438188.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 353385.mp3

 93%|█████████▎| 702/751 [12:23<00:18,  2.58it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 317710.mp3

 94%|█████████▎| 703/751 [12:23<00:21,  2.27it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 208726.mp3

 94%|█████████▎| 704/751 [12:24<00:19,  2.44it/s]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 152233.mp3

 94%|█████████▍| 705/751 [12:25<00:24,  1.86it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 152232.mp3

 94%|█████████▍| 706/751 [12:26<00:32,  1.39it/s]

read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 115474.mp3

 94%|█████████▍| 707/751 [12:26<00:29,  1.50it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 94399.mp3

 94%|█████████▍| 708/751 [12:27<00:25,  1.71it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 56957.mp3

 94%|█████████▍| 709/751 [12:27<00:20,  2.08it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 56955.mp3

 95%|█████████▍| 710/751 [12:27<00:16,  2.43it/s]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 56598.mp3

 95%|█████████▍| 712/751 [12:28<00:11,  3.35it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 56597.mp3
read_audio_data

 95%|█████████▍| 713/751 [12:28<00:11,  3.26it/s]

read_audio_data: complete, read  4 chunks.
analyze_recording 55774.mp3
read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 55773.mp3

 95%|█████████▌| 714/751 [12:29<00:19,  1.92it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 55768.mp3

 95%|█████████▌| 715/751 [12:29<00:17,  2.05it/s]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 14598.mp3

 95%|█████████▌| 716/751 [12:30<00:21,  1.65it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 1037804.mp3

 95%|█████████▌| 717/751 [12:30<00:17,  1.92it/s]

read_audio_data
read_audio_data: complete, read  92 chunks.
analyze_recording 525027.mp3

 96%|█████████▌| 718/751 [12:38<01:27,  2.67s/it]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 438184.mp3

 96%|█████████▌| 719/751 [12:39<01:03,  2.00s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 438181.mp3

 96%|█████████▌| 721/751 [12:39<00:32,  1.09s/it]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 438171.mp3
read_audio_data

 96%|█████████▌| 722/751 [12:39<00:23,  1.23it/s]

read_audio_data: complete, read  3 chunks.
analyze_recording 416105.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording 389155.mp3

 96%|█████████▋| 724/751 [12:40<00:13,  2.01it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 387417.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 382478.mp3

 97%|█████████▋| 725/751 [12:40<00:10,  2.42it/s]

read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 380717.mp3

 97%|█████████▋| 726/751 [12:40<00:09,  2.68it/s]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 339988.mp3

 97%|█████████▋| 727/751 [12:41<00:15,  1.60it/s]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 245510.mp3

 97%|█████████▋| 728/751 [12:42<00:11,  2.00it/s]

read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording 127984.mp3

 97%|█████████▋| 729/751 [12:42<00:12,  1.83it/s]

read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording 115476.mp3

 97%|█████████▋| 730/751 [12:43<00:12,  1.64it/s]

read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording 115475.mp3

 97%|█████████▋| 731/751 [12:45<00:22,  1.13s/it]

read_audio_data
read_audio_data: complete, read  33 chunks.
analyze_recording 115473.mp3

 97%|█████████▋| 732/751 [12:48<00:30,  1.62s/it]

read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording 97519.mp3

 98%|█████████▊| 733/751 [12:48<00:21,  1.21s/it]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 94398.mp3

 98%|█████████▊| 734/751 [12:49<00:19,  1.17s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 86181.mp3

 98%|█████████▊| 735/751 [12:50<00:14,  1.09it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 79781.mp3

 98%|█████████▊| 736/751 [12:51<00:14,  1.06it/s]

read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording 78854.mp3

 98%|█████████▊| 737/751 [12:52<00:14,  1.03s/it]

read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording 56984.mp3

 98%|█████████▊| 738/751 [12:52<00:10,  1.23it/s]

read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording 56983.mp3

 99%|█████████▊| 740/751 [12:53<00:07,  1.51it/s]

read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording 56599.mp3
read_audio_data

 99%|█████████▊| 741/751 [12:54<00:05,  1.77it/s]

read_audio_data: complete, read  4 chunks.
analyze_recording 55772.mp3
read_audio_data

 99%|█████████▉| 742/751 [12:54<00:04,  2.19it/s]

read_audio_data: complete, read  2 chunks.
analyze_recording 55771.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording 55770.mp3

 99%|█████████▉| 743/751 [12:54<00:03,  2.28it/s]

read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording 55769.mp3

 99%|█████████▉| 744/751 [12:55<00:03,  2.12it/s]

read_audio_data
read_audio_data: complete, read  68 chunks.
analyze_recording 28629.mp3

 99%|█████████▉| 745/751 [13:00<00:11,  1.99s/it]

read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording 14597.mp3

 99%|█████████▉| 746/751 [13:01<00:08,  1.63s/it]

read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording 435935.mp3

 99%|█████████▉| 747/751 [13:02<00:05,  1.32s/it]

read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording 339989.mp3

100%|█████████▉| 748/751 [13:03<00:03,  1.27s/it]

read_audio_data
read_audio_data: complete, read  76 chunks.
analyze_recording 178618.mp3

100%|█████████▉| 749/751 [13:09<00:05,  2.72s/it]

read_audio_data
read_audio_data: complete, read  76 chunks.
analyze_recording 178616.mp3

100%|█████████▉| 750/751 [13:15<00:03,  3.75s/it]

read_audio_data
read_audio_data: complete, read  71 chunks.
analyze_recording 367892.mp3

100%|██████████| 751/751 [13:21<00:00,  1.07s/it]

Análisis acústico finalizado.
Total de segmentos de cantos (pseudo-etiquetas) detectados: 10951

,archivo_original,especie_esperada,ave_detectada_comun,ave_detectada_cientifico,inicio_segundo,fin_segundo,confianza_birdnet
0,742378.mp3,Turdus ignobilis,Spectacled Parrotlet,Forpus conspicillatus,3.0,6.0,0.106267
1,742378.mp3,Turdus ignobilis,Spectacled Parrotlet,Forpus conspicillatus,6.0,9.0,0.232879
2,742378.mp3,Turdus ignobilis,Black-billed Thrush,Turdus ignobilis,6.0,9.0,0.208953
3,742378.mp3,Turdus ignobilis,Black-billed Thrush,Turdus ignobilis,9.0,12.0,0.391466
4,742378.mp3,Turdus ignobilis,Spectacled Parrotlet,Forpus conspicillatus,12.0,15.0,0.678364

## 8. El Concepto de Pseudo-Ground-Truth e Implicaciones de la Polifonía Acústica

### 8.1. Paisajes Sonoros Reales y Polifonía Acústica
En las ciencias bioacústicas, los registros de campo son inherentemente ruidosos e interactivos. A pesar de que los audios de *Xeno-Canto* son etiquetados por un recolector humano basándose en una especie "focal" (el ave a la que se dirigía el micrófono), el entorno natural es **polifónico**. Esto significa que es común que múltiples individuos de diferentes especies vocalicen de manera simultánea o superpuesta en el tiempo.

Al configurar el analizador de BirdNET con un umbral de sensibilidad bajo (`min_conf=0.10`), permitimos que el modelo débil actúe como un anotador multi-etiqueta activo, detectando cantos de fondo de otras especies colaterales presentes en el mismo archivo.

### 8.2. Implicaciones del Pseudo-Ground-Truth
El conjunto de etiquetas que utilizaremos para entrenar nuestra Red Neuronal Convolucional Recurrente (CRNN) no constituye una verdad de campo biológica absoluta (*ground-truth* generada por ornitólogos humanos), sino una aproximación sistemática generada por un modelo automatizado, denominada **pseudo-ground-truth** [5]. 

Esto introduce ciertas consideraciones estadísticas para nuestra evaluación:
1.  **Imitación de modelo (Distillation)**: El modelo final aprenderá e imitará los criterios y sesgos sistemáticos del clasificador de Cornell. El mAP de validación/test medirá la concordancia de nuestro modelo con las anotaciones de BirdNET, no necesariamente con la realidad biológica pura [5].
2.  **Modelado Multi-Etiqueta**: Dado que múltiples especies pueden vocalizar al mismo tiempo en un mismo frame, el problema no puede modelarse usando funciones de activación excluyentes como *Softmax* con pérdidas de *Categorical Cross Entropy*. En su lugar, el problema se tratará como $C$ problemas de clasificación binaria independientes mediante el uso de la función de activación *Sigmoide* por frame y especie, optimizada con la pérdida de **Entropía Cruzada Binaria (BCE)**.

## 9. Resolución del Bug de Asignación y Filtrado de Especies Objetivo

Como demostraron los resultados crudos del paso 1.7, un audio grabado y catalogado originalmente bajo una especie focal (como `Turdus ignobilis`) frecuentemente captura cantos ambientales de especies ajenas a nuestro listado (como `Forpus conspicillatus`) [5]. 

Si utilizáramos la lógica del notebook original de etiquetar basándonos en la carpeta de origen (`especie_esperada`), estaríamos entrenando al modelo con falsos positivos severos. Para solucionar esta inconsistencia de raíz, ejecutaremos dos acciones de control:
1.  **Filtrado Estricto por Vocabulario**: Descartaremos cualquier detección de BirdNET cuyo nombre científico (`ave_detectada_cientifico`) no pertenezca estrictamente a nuestra lista de 10 especies objetivo de Medellín.
2.  **Columna de Destino Unificada (`especie_target`)**: Crearemos explícitamente la columna `especie_target` igual a `ave_detectada_cientifico`. El cargador de datos del Notebook 03 leerá esta columna de forma exclusiva, rompiendo cualquier dependencia de la carpeta física donde se encuentra almacenado el archivo original, garantizando la fidelidad de las etiquetas temporales [5].

In [7]:
# 1. Medir el volumen inicial de detecciones crudas
total_inicial = len(df_etiquetas_fuertes)

# 2. Filtrar el DataFrame de etiquetas para mantener únicamente nuestras 10 especies
df_etiquetas_filtradas = df_etiquetas_fuertes[
    df_etiquetas_fuertes["ave_detectada_cientifico"].isin(especies_medellin)
].copy()

# 3. Crear explícitamente la columna de mapeo unificado para el modelo final
df_etiquetas_filtradas["especie_target"] = df_etiquetas_filtradas["ave_detectada_cientifico"]

# 4. Calcular el balance resultante
total_final = len(df_etiquetas_filtradas)
descartados = total_inicial - total_final

print("Saneamiento de etiquetas y resolución de bug completado:")
print(f"  - Detecciones crudas de BirdNET: {total_inicial}")
print(f"  - Segmentos descartados (especies de fondo no objetivo): {descartados}")
print(f"  - Segmentos válidos conservados (nuestras 10 especies): {total_final}")

# Mostrar cuántos segmentos reales tenemos para cada una de las especies objetivo en este lote de prueba
print("\nDistribución de segmentos de cantos válidos por especie objetivo:")
print(df_etiquetas_filtradas["especie_target"].value_counts())

# Reemplazar el DataFrame original con la versión ya saneada y filtrada
df_etiquetas_fuertes = df_etiquetas_filtradas.reset_index(drop=True)

# Mostrar los primeros registros de la tabla limpia de etiquetas fuertes
if not df_etiquetas_fuertes.empty:
    display(df_etiquetas_fuertes.head(5))

Saneamiento de etiquetas y resolución de bug completado:
  - Detecciones crudas de BirdNET: 10951
  - Segmentos descartados (especies de fondo no objetivo): 5310
  - Segmentos válidos conservados (nuestras 10 especies): 5641

Distribución de segmentos de cantos válidos por especie objetivo:
especie_target
Zonotrichia capensis       771
Turdus ignobilis           742
Pitangus sulphuratus       707
Thraupis episcopus         682
Crotophaga ani             593
Campylorhynchus griseus    573
Tyrannus melancholicus     492
Thraupis palmarum          475
Troglodytes aedon          371
Pygochelidon cyanoleuca    235
Name: count, dtype: int64

,archivo_original,especie_esperada,ave_detectada_comun,ave_detectada_cientifico,inicio_segundo,fin_segundo,confianza_birdnet,especie_target
0,742378.mp3,Turdus ignobilis,Black-billed Thrush,Turdus ignobilis,6.0,9.0,0.208953,Turdus ignobilis
1,742378.mp3,Turdus ignobilis,Black-billed Thrush,Turdus ignobilis,9.0,12.0,0.391466,Turdus ignobilis
2,742378.mp3,Turdus ignobilis,Black-billed Thrush,Turdus ignobilis,15.0,18.0,0.351664,Turdus ignobilis
3,742378.mp3,Turdus ignobilis,Black-billed Thrush,Turdus ignobilis,18.0,21.0,0.386466,Turdus ignobilis
4,742378.mp3,Turdus ignobilis,Black-billed Thrush,Turdus ignobilis,24.0,27.0,0.247040,Turdus ignobilis

## 10. Persistencia de Metadatos de Audios (`df_metadata_audios.csv`)

Una vez saneado el dataset físico de audios y extraídos los metadatos acústicos reales (como duración medida y tasa de muestreo real de códecs), procedemos a persistir esta información en el almacenamiento local [5].

Este archivo se guardará bajo la ruta `dataset_aves/df_metadata_audios.csv` y representará el inventario primario y registro de auditoría de nuestro corpus acústico [5].

In [8]:
# Guardar el DataFrame de metadatos de audios depurados en disco sin guardar el índice de pandas
df_metadata_completa.to_csv(METADATA_PATH, index=False)

print("Registro de metadatos de audios guardado con éxito:")
print(f"  - Ruta de destino: {os.path.abspath(METADATA_PATH)}")
print(f"  - Cantidad de audios válidos indexados: {len(df_metadata_completa)}")
print(f"  - Tamaño aproximado del archivo en disco: {os.path.getsize(METADATA_PATH) / 1024:.2f} KB")

Registro de metadatos de audios guardado con éxito:
  - Ruta de destino: /home/els4nchez/Pictures/Bird-Recognition-using-BioSED-model/dataset_aves/df_metadata_audios.csv
  - Cantidad de audios válidos indexados: 751
  - Tamaño aproximado del archivo en disco: 211.55 KB

## 11. Persistencia de Etiquetas Fuertes Saneadas (`df_etiquetas_fuertes.csv`)

Una vez que hemos resuelto el bug de asignación cruzada de especies por directorio y hemos filtrado los cantos de fondo para retener únicamente nuestras 10 especies objetivo de Medellín, procedemos a persistir la matriz de etiquetas fuertes en el disco [5].

Este archivo se guardará bajo la ruta `dataset_aves/df_etiquetas_fuertes.csv` [5]. Es el archivo más crítico para el modelado, ya que representa la "fuente de verdad débil" (*pseudo-ground-truth*) que el generador de lotes (*Data Loader*) consultará en el Notebook 03 para mapear de forma exacta qué frames de tiempo tienen cantos activos por especie [5].

In [9]:
# Guardar el DataFrame de etiquetas fuertes filtradas en disco sin guardar el índice de pandas
df_etiquetas_fuertes.to_csv(LABELS_PATH, index=False)

print("Registro de etiquetas fuertes guardado con éxito:")
print(f"  - Ruta de destino: {os.path.abspath(LABELS_PATH)}")
print(f"  - Cantidad de segmentos de canto indexados: {len(df_etiquetas_fuertes)}")
print(f"  - Tamaño aproximado del archivo en disco: {os.path.getsize(LABELS_PATH) / 1024:.2f} KB")

Registro de etiquetas fuertes guardado con éxito:
  - Ruta de destino: /home/els4nchez/Pictures/Bird-Recognition-using-BioSED-model/dataset_aves/df_etiquetas_fuertes.csv
  - Cantidad de segmentos de canto indexados: 5641
  - Tamaño aproximado del archivo en disco: 644.77 KB

## 12. Consolidación de Estadísticas Descriptivas del Dataset

Para auditar el balance y la distribución de datos antes de transferir el corpus al Notebook 02 (Análisis Exploratorio de Datos), consolidaremos un reporte descriptivo unificado. 

Este reporte cruzará la información del inventario de audios y del dataset de etiquetas fuertes, mostrando para cada una de las 10 especies objetivo:
1.  La cantidad de archivos de audio físicamente válidos en disco [5].
2.  La cantidad total de eventos de canto (*sound events*) temporalmente activos.
3.  La tasa promedio de eventos por archivo de audio (densidad acústica).

Adicionalmente, calcularemos una métrica global de control de calidad que registra cuántos audios corruptos debieron ser eliminados y depurados del sistema [5].

In [10]:
# 1. Contar la distribución física de audios válidos por especie
audios_validos_serie = df_metadata_completa["especie_esperada"].value_counts()

# 2. Contar la cantidad de segmentos de canto válidos por especie objetivo
eventos_validos_serie = df_etiquetas_fuertes["especie_target"].value_counts()

# 3. Consolidar ambas series en un DataFrame descriptivo estructurado
df_resumen = pd.DataFrame({
    "Audios Válidos": audios_validos_serie,
    "Eventos de Canto": eventos_validos_serie
})

# Saneamiento de nulos (por si alguna especie no registró cantos en este lote de prueba rápido)
df_resumen.fillna(0, inplace=True)
df_resumen = df_resumen.astype(int)

# Calcular métrica de densidad acústica derivada
df_resumen["Tasa Eventos/Audio"] = (df_resumen["Eventos de Canto"] / df_resumen["Audios Válidos"]).round(2)

df_resumen.index.name = "Especie"
df_resumen.reset_index(inplace=True)

# 4. Calcular consolidados globales de auditoría de descargas y descartes
total_intentados = len(especies_medellin) * MAX_ARCHIVOS_POR_ESPECIE
total_validos = len(df_metadata_completa)
total_descartados = total_intentados - total_validos

print("==============================================")
print("        REPORTE DE AUDITORÍA DEL DATASET      ")
print("==============================================")
print(f"Total de archivos de audio intentados: {total_intentados}")
print(f"Total de archivos de audio válidos:    {total_validos}")
print(f"Total de archivos de audio descartados: {total_descartados}")
print(f"Total de segmentos de cantos activos:   {df_resumen['Eventos de Canto'].sum()}")
print("==============================================\n")

# Mostrar la tabla descriptiva formateada
display(df_resumen)

==============================================
        REPORTE DE AUDITORÍA DEL DATASET
==============================================
Total de archivos de audio intentados: 1200
Total de archivos de audio válidos:    751
Total de archivos de audio descartados: 449
Total de segmentos de cantos activos:   5641
==============================================

,Especie,Audios Válidos,Eventos de Canto,Tasa Eventos/Audio
0,Campylorhynchus griseus,74,573,7.74
1,Crotophaga ani,83,593,7.14
2,Pitangus sulphuratus,99,707,7.14
3,Pygochelidon cyanoleuca,33,235,7.12
4,Thraupis episcopus,71,682,9.61
5,Thraupis palmarum,46,475,10.33
6,Troglodytes aedon,99,371,3.75
7,Turdus ignobilis,60,742,12.37
8,Tyrannus melancholicus,86,492,5.72
9,Zonotrichia capensis,100,771,7.71

## 13. Verificación Final del Dataset y Transición a Volumen Académico Completo

### 13.1. Verificación Programática de Estructuras
Antes de dar por concluida la ejecución, correremos una auditoría programática final. Esta celda inspeccionará el sistema de archivos local para certificar que contamos con los índices de metadatos, tablas de etiquetas fuertes y las carpetas de audio requeridas de forma unificada para los Notebooks 02 (EDA), 03 (Entrenamiento), 04 (Evaluación) y 05 (Dashboard Demo) [5].

### 13.2. Recordatorio: Transición al Volumen de Entrenamiento Real (120 Audios)
Hasta este momento, este notebook se ha ejecutado bajo un modo de desarrollo controlado con `MAX_ARCHIVOS_POR_ESPECIE = 5` para garantizar que la depuración de dependencias, la API de Xeno-Canto y las pseudo-etiquetas de BirdNET fluyan sinNameErrors ni bloqueos de red [5].

Para generar el conjunto de datos de entrenamiento real para la CRNN de tu compañero:
1.  Sube a la celda del **Paso 1.5** de este notebook.
2.  Modifica la variable: `MAX_ARCHIVOS_POR_ESPECIE = 120`.
3.  En la barra superior de Jupyter, selecciona **Kernel -> Restart & Run All** (Reiniciar y Ejecutar todo).
4.  El notebook se ejecutará de forma completamente automatizada de principio a fin, descargará los 1200 archivos de audio de Xeno-Canto, aplicará el filtro preventivo de decodificación, ejecutará la extracción de BirdNET de todos ellos y persistirá los archivos `.csv` finales listos para el modelado real [5].

In [11]:
# Inicializar contador de inconsistencias
errores_encontrados = 0

print("=== INICIANDO AUDITORÍA AUTOMATIZADA DE CONSISTENCIA ===")

# 1. Comprobar archivo de metadatos de audio
if os.path.exists(METADATA_PATH):
    df_test_meta = pd.read_csv(METADATA_PATH)
    if len(df_test_meta) > 0:
        print(f"  [OK] df_metadata_audios.csv presente. Registros indexados: {len(df_test_meta)}")
    else:
        print("  [ERROR] df_metadata_audios.csv se encuentra vacío en disco.")
        errores_encontrados += 1
else:
    print("  [ERROR] No se encuentra el archivo df_metadata_audios.csv en la ruta esperada.")
    errores_encontrados += 1

# 2. Comprobar archivo de etiquetas fuertes filtradas
if os.path.exists(LABELS_PATH):
    df_test_labels = pd.read_csv(LABELS_PATH)
    if len(df_test_labels) > 0:
        print(f"  [OK] df_etiquetas_fuertes.csv presente. Segmentos de canto indexados: {len(df_test_labels)}")
    else:
        print("  [ERROR] df_etiquetas_fuertes.csv se encuentra vacío en disco.")
        errores_encontrados += 1
else:
    print("  [ERROR] No se encuentra el archivo df_etiquetas_fuertes.csv en la ruta esperada.")
    errores_encontrados += 1

# 3. Comprobar carpetas físicas de especies e inventario real de audios MP3 en disco
carpetas_especie_encontradas = 0
audios_totales_contados = 0

for especie in especies_medellin:
    nombre_carpeta = especie.replace(" ", "_")
    ruta_carpeta = os.path.join(BASE_DIR, nombre_carpeta)
    
    if os.path.isdir(ruta_carpeta):
        carpetas_especie_encontradas += 1
        archivos_mp3 = [f for f in os.listdir(ruta_carpeta) if f.endswith(".mp3")]
        audios_totales_contados += len(archivos_mp3)
    else:
        print(f"  [ERROR] No existe la carpeta de almacenamiento de audio para: {especie}")
        errores_encontrados += 1

print(f"  [OK] Subdirectorios taxonómicos localizados: {carpetas_especie_encontradas}/10")
print(f"  [OK] Archivos físicos de audio .mp3 detectados: {audios_totales_contados}")

print("\n=== DICTAMEN FINAL DE LA AUDITORÍA ===")
if errores_encontrados == 0:
    print("ESTADO: DATASET CONSISTENTE")
    print("El notebook ha generado toda la estructura física e índices de control necesarios de forma correcta.")
else:
    print(f"ESTADO: INCONSISTENTE. Se identificaron {errores_encontrados} inconsistencias que deben corregirse.")

=== INICIANDO AUDITORÍA AUTOMATIZADA DE CONSISTENCIA ===
  [OK] df_metadata_audios.csv presente. Registros indexados: 751
  [OK] df_etiquetas_fuertes.csv presente. Segmentos de canto indexados: 5641
  [OK] Subdirectorios taxonómicos localizados: 10/10
  [OK] Archivos físicos de audio .mp3 detectados: 751

=== DICTAMEN FINAL DE LA AUDITORÍA ===
ESTADO: DATASET CONSISTENTE
El notebook ha generado toda la estructura física e índices de control necesarios de forma correcta.